In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/DATA SET /carriers.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DATA SET /customers.csv')
df3 = pd.read_csv('/content/drive/MyDrive/DATA SET /customs.csv')
df4 = pd.read_csv('/content/drive/MyDrive/DATA SET /products.csv')
df5 = pd.read_csv('/content/drive/MyDrive/DATA SET /routes.csv')
df6 = pd.read_csv('/content/drive/MyDrive/DATA SET /shipment_delivery_history.csv')
df7 = pd.read_csv('/content/drive/MyDrive/DATA SET /shipments.csv')
df8 = pd.read_csv('/content/drive/MyDrive/DATA SET /vehicles.csv')
df9 = pd.read_csv('/content/drive/MyDrive/DATA SET /warehouses.csv')
df10 = pd.read_csv('/content/drive/MyDrive/DATA SET /weather.csv')

##Dataset Overview - carriers.csv (df1)

In [ ]:
df1.shape

(30, 7)

##**Interpretation** :


*   This command returns the total number of
rows and columns in the dataset.
*   Rows represent the number of carrier records.
*   Columns represent the number of attributes describing each carrier.

In [ ]:
print("Number of Rows :", df1.shape[0])
print("Number of Columns :", df1.shape[1])

Number of Rows : 30
Number of Columns : 7

##**Interpretation** :



*   The dataset contains 30 rows, meaning information for 30 different carriers.
*   It contains 7 columns, each describing a different characteristic of a carrier.

In [ ]:
df1.columns

Index(['carrier_id', 'carrier_name', 'carrier_type', 'average_rating',
       'fleet_size', 'years_of_service', 'headquarters'],
      dtype='object')

##**Interpretation** :



The dataset contains the following columns:
*   carrier_id
*   carrier_name
*   carrier_type
*   average_rating
*   fleet_size
*   years_of_service
*   headquarters

These columns describe each logistics carrier and its operational characteristics.

In [ ]:
df1.dtypes

carrier_id           object
carrier_name         object
carrier_type         object
average_rating      float64
fleet_size          float64
years_of_service      int64
headquarters         object
dtype: object

##**Interpretation** :

This helps identify whether each column is:

*   Integer (int64)
*   Decimal (float64)
*   Text (object)


Correct data types are important before performing data analysis and model building.

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   carrier_id        30 non-null     object
 1   carrier_name      30 non-null     object
 2   carrier_type      30 non-null     object
 3   average_rating    30 non-null     float64
 4   fleet_size        28 non-null     float64
 5   years_of_service  30 non-null     int64
 6   headquarters      30 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.8+ KB

##**Interpretation** :

The info() function provides:

*   Total entries
*   Column names
*   Data types
*   Non-null values
*   Memory usage

This helps determine whether the dataset contains missing values and whether the data types are appropriate.

In [ ]:
df1.head()

,carrier_id,carrier_name,carrier_type,average_rating,fleet_size,years_of_service,headquarters
0,8ece1ccd-e714-4f7e-9cbe-ae2b70fbfe8e,Adams Ltd Freight,Rail,3.42,174.0,16,Mumbai
1,3da6490d-b4a8-4ae9-8e6f-bc2b4559e53f,Gallagher and Sons Logistics,Road,4.76,469.0,8,Vancouver
2,3b435d96-04e0-4c24-b4f2-2f00145cb906,"Bradford, Salinas and Kelly Freight",Road,2.53,404.0,33,Surat
3,dbad2d39-550a-4a63-a01f-02661e0e712b,Thompson PLC Logistics,Sea,4.15,NaN,15,Rio de Janeiro
4,e939f0cc-3244-40b3-884d-8f4e71455344,Drake-Wolfe Cargo,Sea,3.12,242.0,4,Kolkata

##**Interpretation** :

The first five rows provide a quick overview of the dataset structure and verify that the data has been loaded correctly.

In [ ]:
df1.tail()

,carrier_id,carrier_name,carrier_type,average_rating,fleet_size,years_of_service,headquarters
25,2091e662-39cf-489c-9e58-8066d5101a55,Reed LLC Logistics,Rail,4.37,233.0,21,Pune
26,bebdea49-529d-421e-8d97-7a4698581b23,Fields Inc Shipping,Road,3.33,57.0,26,Melbourne
27,aabfdc24-e492-4483-a2cc-ca4e47359860,"Santiago, Daniel and Rogers Logistics",Road,3.11,427.0,6,London
28,c3b1b3c0-b731-41b7-9fff-aefd5e586db0,Baker and Sons Freight,Rail,2.73,491.0,22,Ho Chi Minh City
29,1b55fff6-046a-4456-9cb0-b8cd21addf5a,"Jones, Scott and Rodriguez Logistics",Air,2.94,437.0,30,Karachi

##**Interpretation** :

The last five rows help verify that the entire dataset has been loaded without truncation or corruption.

In [ ]:
df1.describe()

       average_rating  fleet_size  years_of_service
count       30.000000   28.000000         30.000000
mean         3.592333  314.642857         21.166667
std          0.754900  136.456265         11.255905
min          2.060000   28.000000          4.000000
25%          3.112500  222.250000         10.500000
50%          3.400000  363.000000         22.000000
75%          4.210000  429.500000         30.750000
max          5.000000  491.000000         38.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df1.isnull().sum()

carrier_id          0
carrier_name        0
carrier_type        0
average_rating      0
fleet_size          2
years_of_service    0
headquarters        0
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df1.isnull().sum()/len(df1))*100

carrier_id          0.000000
carrier_name        0.000000
carrier_type        0.000000
average_rating      0.000000
fleet_size          6.666667
years_of_service    0.000000
headquarters        0.000000
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df1.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df1.nunique()

carrier_id          30
carrier_name        30
carrier_type         4
average_rating      29
fleet_size          27
years_of_service    22
headquarters        22
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
print("Total Memory Usage:", round(df1.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 8.78 KB

##**Interpretation** :

This displays the memory consumed by each column. It helps evaluate storage requirements and identify opportunities for optimization.

##Important Information About carriers.csv

*   It is a master dataset containing information about logistics carriers.
*   Each row represents one carrier company.
*   The dataset contains carrier performance and operational characteristics.
*   It is linked to the main shipments.csv dataset using the carrier_id column.
*   This table provides contextual information rather than shipment-level records.

##Columns and Their Importance

| Column           | Importance for Delay Prediction                                       |
| ---------------- | --------------------------------------------------------------------- |
| carrier_id       | Used for joining tables; not used directly as a feature               |
| carrier_name     | Identifier only; generally excluded from modeling                     |
| carrier_type     | Important feature, as transport mode influences delivery time         |
| average_rating   | Important; higher-rated carriers may have better delivery performance |
| fleet_size       | Important; larger fleets may improve operational capacity             |
| years_of_service | Important; experienced carriers may perform more reliably             |
| headquarters     | Can be useful if converted into geographic features                   |

##Dataset Overview - customers.csv (df2)

In [ ]:
df2.shape

print("Number of Rows :", df2.shape[0])
print("Number of Columns :", df2.shape[1])

Number of Rows : 624
Number of Columns : 9

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df2.columns

Index(['customer_id', 'customer_name', 'customer_type', 'industry', 'city',
       'state', 'country', 'registration_date', 'customer_status'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df2.dtypes

customer_id          object
customer_name        object
customer_type        object
industry             object
city                 object
state                object
country              object
registration_date    object
customer_status      object
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624 entries, 0 to 623
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        624 non-null    object
 1   customer_name      624 non-null    object
 2   customer_type      615 non-null    object
 3   industry           587 non-null    object
 4   city               624 non-null    object
 5   state              609 non-null    object
 6   country            624 non-null    object
 7   registration_date  618 non-null    object
 8   customer_status    624 non-null    object
dtypes: object(9)
memory usage: 44.0+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df2.head()

,customer_id,customer_name,customer_type,industry,city,state,country,registration_date,customer_status
0,29a04ac8-f781-44fd-816b-f5e562061527,"Rodriguez, Figueroa and Sanchez",Business,Electronics,Pune,Maharashtra,India,2021-05-05,Active
1,3dfeb7e6-5401-425a-9cc4-e67943574bdf,Rhodes PLC,Business,Manufacturing,Singapore,Singapore,Singapore,2021-01-11,Active
2,28c08869-6ed0-4f9d-8fa8-2c1384d247e9,Johnson-Davis,Business,Manufacturing,Bengaluru,Karnataka,India,2021-11-23,Active
3,a08b0662-e4a2-4c08-a9eb-326c8122cd81,"Johnson, Gonzalez and Santos",Business,Automotive,Antwerp,Antwerp,Belgium,2023-09-29,Active
4,6848ceba-25e3-4dbb-93de-fa62f1982e62,Cole LLC,Individual,Automotive,Jeddah,Mecca,Saudi Arabia,2025-04-22,Active

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df2.tail()

,customer_id,customer_name,customer_type,industry,city,state,country,registration_date,customer_status
619,8805c2cc-3477-46bd-91c2-7931bf85eec8,Garrison and Sons,Individual,Automotive,Karachi,Sindh,Pakistan,2021-09-12,Active
620,8309725c-0a5c-460f-b553-07cf3d9f45c2,Johnson-Davis Inc,Business,Manufacturing,Bengaluru,Karnataka,India,2021-11-23,Active
621,5d232fce-9391-4983-8f39-8773747a2f87,Cole PLC.,Individual,E-commerce,Surat,Gujarat,India,2023-05-10,Active
622,2daf04d8-7c95-4755-a5fb-9dc17fde1011,Warren Inc.,Individual,Food Processing,Hamburg,Hamburg,Germany,2026-02-10,Active
623,7cd5beff-f217-4f3e-8275-53b85b3eab67,Cooper Inc Pvt Ltd,Business,Food Processing,Rio de Janeiro,Rio de Janeiro,Brazil,2023-05-17,Inactive

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df2.describe()

       average_rating  fleet_size  years_of_service
count       30.000000   28.000000         30.000000
mean         3.592333  314.642857         21.166667
std          0.754900  136.456265         11.255905
min          2.060000   28.000000          4.000000
25%          3.112500  222.250000         10.500000
50%          3.400000  363.000000         22.000000
75%          4.210000  429.500000         30.750000
max          5.000000  491.000000         38.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df2.isnull().sum()

customer_id           0
customer_name         0
customer_type         9
industry             37
city                  0
state                15
country               0
registration_date     6
customer_status       0
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df2.isnull().sum()/len(df1))*100

customer_id            0.000000
customer_name          0.000000
customer_type         30.000000
industry             123.333333
city                   0.000000
state                 50.000000
country                0.000000
registration_date     20.000000
customer_status        0.000000
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df2.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df2.nunique()

carrier_id          30
carrier_name        30
carrier_type         4
average_rating      29
fleet_size          27
years_of_service    22
headquarters        22
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df2.sample(5, random_state=42)

,customer_id,customer_name,customer_type,industry,city,state,country,registration_date,customer_status
446,2a903c3d-50c2-4c5a-9f31-4cf52e698dfc,"Peterson, Gomez and Ingram",Business,Textiles,Melbourne,Victoria,Australia,2024-10-13,Active
496,2bfd9b7b-3ba5-4746-ab0c-eb80ab2aa0b0,Valdez LLC,Business,Textiles,Surat,Gujarat,India,2021-03-21,Active
215,3a0c107d-f7e4-4178-a1a2-ea45924aecdb,Jones LLC,Individual,Food Processing,Karachi,Sindh,Pakistan,2022-07-09,Active
212,e7343707-2a02-49ae-96d4-d7cae91a2b35,"Pollard, Simpson and Johnson",Business,E-commerce,Sao Paulo,Sao Paulo,Brazil,2023-06-28,Active
479,482eba97-c839-43c5-b75e-2a4157b1cc9c,Mendez-Robinson,Business,Electronics,Hamburg,Hamburg,Germany,2021-04-22,Active

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df2.memory_usage(deep=True)

print("Total Memory Usage:", round(df2.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 334.57 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The customers.csv dataset contains customer-related information used in the logistics system. Each record represents a unique customer and includes details such as customer type, industry, and geographic location. This dataset serves as a master data table and is connected to the shipments.csv dataset through the customer_id field. The dataset appears suitable for analysis after verifying missing values and duplicate records. Customer-related features can contribute to identifying shipment patterns and may improve the performance of the shipment delay prediction model when combined with shipment, route, and carrier information.

##Useful Features for Delay Prediction

1.Customer Type

2.Industry

3.City

4.State

5.Country
##Features Not Used Directly

1.Customer ID (used only for joining tables)

2.Customer Name (if present, usually not useful for prediction)

##Important Information about customers.csv

| Attribute       | Description                                            |
| --------------- | ------------------------------------------------------ |
| Dataset Name    | customers.csv                                          |
| DataFrame       | df2                                                    |
| Dataset Type    | Master Dataset                                         |
| Primary Key     | customer_id                                            |
| Related Dataset | shipments.csv                                          |
| Relationship    | One Customer → Many Shipments                          |
| Purpose         | Stores customer details used for shipment transactions |

##Dataset Overview - customs.csv (df3)

In [ ]:
df3.shape

print("Number of Rows :", df3.shape[0])
print("Number of Columns :", df3.shape[1])

Number of Rows : 1800
Number of Columns : 6

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df3.columns

Index(['customs_id', 'customs_required', 'documentation_complete',
       'inspection_required', 'cargo_type', 'destination_country'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df3.dtypes

customs_id                object
customs_required            bool
documentation_complete    object
inspection_required       object
cargo_type                object
destination_country       object
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customs_id              1800 non-null   object
 1   customs_required        1800 non-null   bool
 2   documentation_complete  1764 non-null   object
 3   inspection_required     1745 non-null   object
 4   cargo_type              1800 non-null   object
 5   destination_country     1800 non-null   object
dtypes: bool(1), object(5)
memory usage: 72.2+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df3.head()

,customs_id,customs_required,documentation_complete,inspection_required,cargo_type,destination_country
0,d7ddd34e-151b-4058-b8ee-93ed4c6826ae,False,True,False,Pharmaceuticals,UK
1,39f37e26-87c5-4e2e-aa18-7cf922148905,True,True,False,Food & Beverage,India
2,8679a64b-484b-4cc6-b937-c3fe7de7c513,True,True,True,Textiles,China
3,efc4456c-e459-445a-b456-c2150ca8aa87,True,True,False,Furniture,India
4,516ee0f2-6417-4038-98fa-703ac7a53938,False,True,False,Automotive Parts,Belgium

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df3.tail()

,customs_id,customs_required,documentation_complete,inspection_required,cargo_type,destination_country
1795,3e591d21-b0a5-4a7f-9a54-93f57872f5cb,False,True,False,Toys,Thailand
1796,f469d5f7-b214-4480-82cc-0509cce029a6,True,True,False,Machinery,Canada
1797,7506c6cf-9b10-4a2d-b800-ba9866fac22a,False,True,False,Pharmaceuticals,South Africa
1798,427dc692-ee88-411d-9cb1-ae090c895805,True,True,False,Chemicals,Australia
1799,1bf05663-b5a9-4f2d-a41c-f770c21784d7,True,True,False,Toys,China

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df3.sample(5, random_state=42)

,customs_id,customs_required,documentation_complete,inspection_required,cargo_type,destination_country
1591,528ac176-daf7-412d-b10c-16d5c583b3db,True,True,True,Chemicals,Pakistan
943,b15f9713-0f36-490a-9450-b46aeafa2f7e,False,True,False,Chemicals,Saudi Arabia
869,6d3f074f-983d-471b-bf94-0b2e80b7c93c,True,False,True,Toys,China
162,85dddc6b-9574-441a-8db5-ea0f01a91daf,True,False,False,Machinery,Australia
1271,1a1a00cb-d760-4497-87c1-adcc9da0e20b,True,True,False,Furniture,Vietnam

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df3.memory_usage(deep=True)

print("Total Memory Usage:", round(df2.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 334.57 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The customs.csv dataset contains customs clearance information associated with shipments, particularly for international deliveries. Each record includes details such as customs requirements, documentation status, inspection requirements, cargo type, and destination country. This dataset is linked to the shipments.csv dataset through the customs_id field. Customs-related factors can significantly influence shipment delays because incomplete documentation or mandatory inspections may increase delivery time. Therefore, this dataset provides valuable features for shipment delay prediction after handling any missing values and ensuring data quality.

##Important Information about customs.csv

| Attribute           | Description                                                   |
| ------------------- | ------------------------------------------------------------- |
| **Dataset Name**    | customs.csv                                                   |
| **DataFrame**       | df3                                                           |
| **Dataset Type**    | Transactional / Reference Dataset                             |
| **Primary Key**     | customs_id                                                    |
| **Related Dataset** | shipments.csv                                                 |
| **Relationship**    | One Customs Record → Many Shipments                           |
| **Purpose**         | Stores customs clearance and inspection details for shipments |

##Useful Features for Delay Prediction

1.Customs Required

2.Documentation Complete

3.Inspection Required

4.Cargo Type

5.Destination Country

##Features Not Used Directly

1.Customs ID (used only for joining with the shipments dataset)

##Dataset Overview - products.csv (df4)

In [ ]:
df4.shape

print("Number of Rows :", df4.shape[0])
print("Number of Columns :", df4.shape[1])

Number of Rows : 164
Number of Columns : 10

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df4.columns

Index(['product_id', 'product_name', 'category', 'hs_code', 'hazardous',
       'perishable', 'temperature_controlled', 'fragile', 'weight_per_unit',
       'supplier_name'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df4.dtypes

product_id                 object
product_name               object
category                   object
hs_code                   float64
hazardous                    bool
perishable                   bool
temperature_controlled       bool
fragile                      bool
weight_per_unit           float64
supplier_name              object
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              164 non-null    object
 1   product_name            164 non-null    object
 2   category                164 non-null    object
 3   hs_code                 153 non-null    float64
 4   hazardous               164 non-null    bool
 5   perishable              164 non-null    bool
 6   temperature_controlled  164 non-null    bool
 7   fragile                 164 non-null    bool
 8   weight_per_unit         158 non-null    float64
 9   supplier_name           154 non-null    object
dtypes: bool(4), float64(2), object(4)
memory usage: 8.5+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df4.head()

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
0,11ee7365-3de8-4f2e-b4b2-fc0202a0f2c3,Local Automotive Part,Automotive Parts,4022.33,False,False,True,False,7.09,Jones-Williams
1,257ace85-8350-43e8-b2f2-6161a558e97a,See Pharmaceutical,Pharmaceuticals,8365.85,False,True,False,False,16.25,Johnson LLC
2,0dad9f1e-5893-4421-b3a7-5cfec833e6ba,Raise Textile,Textiles,2667.78,False,False,False,False,31.80,Byrd and Sons
3,43fac5b7-251a-479f-88f3-c5a8e89e838d,Wonder Furniture,Furniture,9646.91,False,False,False,True,4.39,"Sanchez, Thompson and Moore"
4,373483cd-db6a-4d99-adec-0b6f9981f1ea,Opportunity Food & Beverage,Food & Beverage,8501.89,False,False,False,False,14.26,Mullen-Hall

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df4.tail()

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
159,eac56cb7-6578-4aed-8e21-5267c69af4dc,Early Chemical,Chemicals,9571.35,False,False,False,False,4.51,Garcia Ltd
160,f5b7a533-759a-4c57-a367-4576d05294cf,Election Furniture,Furniture,2892.49,False,False,False,False,0.65,Ruiz Group
161,ea9500ea-ca7c-426f-8789-a3881557c028,Keep Textile,Textiles,2404.95,False,False,False,False,0.20,NaN
162,ef0afa43-ce55-4117-8007-c5c831f747e5,Case Food & Beverage,Food & Beverage,7089.43,False,False,True,True,11.65,NaN
163,1030dc7d-ada2-4923-8d46-4fff1712e9dc,Later Textile,Textiles,9225.96,False,False,False,False,1.14,Forbes and Sons

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df4.describe()

           hs_code  weight_per_unit
count   153.000000       158.000000
mean   5200.495163         8.183544
std    2741.522349         7.838489
min    1017.370000         0.200000
25%    2715.190000         2.532500
50%    4707.980000         5.755000
75%    7520.740000        11.740000
max    9849.430000        49.230000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df4.isnull().sum()

product_id                 0
product_name               0
category                   0
hs_code                   11
hazardous                  0
perishable                 0
temperature_controlled     0
fragile                    0
weight_per_unit            6
supplier_name             10
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df4.isnull().sum()/len(df1))*100

product_id                 0.000000
product_name               0.000000
category                   0.000000
hs_code                   36.666667
hazardous                  0.000000
perishable                 0.000000
temperature_controlled     0.000000
fragile                    0.000000
weight_per_unit           20.000000
supplier_name             33.333333
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df4.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df4.nunique()

product_id                164
product_name              160
category                   10
hs_code                   149
hazardous                   2
perishable                  2
temperature_controlled      2
fragile                     2
weight_per_unit           145
supplier_name             152
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df4.sample(5, random_state=42)

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
135,2ed0325a-eca1-4411-a11a-5c8b60461a3c,Generation Toy,Toys,4937.17,False,False,False,False,9.94,Davis and Sons
115,dd159eb2-f7cd-4853-84bb-cc19107aa0ab,Spring Electronic,Electronics,9561.63,False,True,False,False,0.23,Oconnor PLC
131,a8d27255-f1bc-49f0-8523-36a02a0dd901,Man Chemical,Chemicals,5511.64,False,False,False,False,9.49,Russell-Herrera
55,91df6507-f774-4d9c-8c2d-bd9a94b1d5f9,Later Textile,Textiles,9225.96,False,False,False,False,1.14,Forbes and Sons
95,2d222bb3-fb89-4b71-aba1-d864c062d89f,Continue Machinery,Machinery,2453.95,False,False,False,False,13.24,Smith and Sons

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df4.memory_usage(deep=True)

print("Total Memory Usage:", round(df2.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 334.57 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The products.csv dataset contains detailed information about the products transported through the logistics system. Each record represents a unique product and includes attributes such as product category, weight, hazardous status, perishability, temperature control requirements, and supplier information. This dataset is linked to the shipments.csv dataset through the product_id field. Product characteristics can directly influence shipment handling, transportation requirements, and delivery time. Therefore, this dataset provides valuable information for understanding shipment behavior and improving the performance of a shipment delay prediction model.

##Important Information about products.csv

| Attribute           | Description                                                |
| ------------------- | ---------------------------------------------------------- |
| **Dataset Name**    | products.csv                                               |
| **DataFrame**       | df4                                                        |
| **Dataset Type**    | Master Dataset                                             |
| **Primary Key**     | product_id                                                 |
| **Related Dataset** | shipments.csv                                              |
| **Relationship**    | One Product → Many Shipments                               |
| **Purpose**         | Stores product characteristics used in shipment operations |

##Useful Features for Delay Prediction

1.Product Category

2.Product Weight

3.Hazardous Flag

4.Perishable Flag

5.Temperature Controlled Flag

6.Fragile Flag

##Features Not Used Directly

1.Product ID (used only for joining datasets)

2.Product Name (identifier; generally not used directly in model training)

3.Supplier Name (unless supplier performance is specifically analyzed)

##Dataset Overview - routes.csv (df5)

In [ ]:
df5.shape

print("Number of Rows :", df5.shape[0])
print("Number of Columns :", df5.shape[1])

Number of Rows : 300
Number of Columns : 11

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df5.columns

Index(['route_id', 'origin_city', 'destination_city', 'origin_country',
       'destination_country', 'origin_port', 'destination_port', 'distance_km',
       'average_transit_days', 'route_risk', 'traffic_index'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df5.dtypes

route_id                 object
origin_city              object
destination_city         object
origin_country           object
destination_country      object
origin_port              object
destination_port         object
distance_km             float64
average_transit_days      int64
route_risk               object
traffic_index           float64
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   route_id              300 non-null    object
 1   origin_city           300 non-null    object
 2   destination_city      300 non-null    object
 3   origin_country        300 non-null    object
 4   destination_country   300 non-null    object
 5   origin_port           300 non-null    object
 6   destination_port      300 non-null    object
 7   distance_km           300 non-null    float64
 8   average_transit_days  300 non-null    int64
 9   route_risk            294 non-null    object
 10  traffic_index         291 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 25.9+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df5.head()

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
0,9e78f107-814c-477e-9d1f-45f98e13055d,Jeddah,Chicago,Saudi Arabia,USA,Port of Jeddah,Port of Chicago,12023.7,17,Low,99.0
1,53dfd4ec-4ed2-41fa-ab72-e023d823a48b,Ho Chi Minh City,Antwerp,Vietnam,Belgium,Port of Ho Chi Minh City,Port of Antwerp,13967.0,15,Medium,63.0
2,fb541cb9-674f-4ace-a42f-d329f4695f5e,Bengaluru,Chicago,India,USA,Port of Bengaluru,Port of Chicago,3441.6,7,High,42.0
3,6a1da14d-b39f-4fd7-82ac-0eab1209299f,Antwerp,Ahmedabad,Belgium,India,Port of Antwerp,Port of Ahmedabad,641.7,6,High,99.0
4,f01765d1-46b8-4301-ae38-c3d463322c21,Jeddah,Mumbai,Saudi Arabia,India,Port of Jeddah,Port of Mumbai,5803.8,7,Medium,NaN

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df5.tail()

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
295,9962d450-44ea-4af9-ad26-3459d7875481,Jeddah,Singapore,Saudi Arabia,Singapore,Port of Jeddah,Port of Singapore,9524.7,11,Low,58.0
296,fe29039e-5f23-4576-b1f6-6e539620aae3,Delhi,Shenzhen,India,China,Port of Delhi,Port of Shenzhen,4500.3,29,Low,92.0
297,22c1a25e-190d-488d-8117-fd1f76720e05,Hong Kong,Rio de Janeiro,China,Brazil,Port of Hong Kong,Port of Rio de Janeiro,11885.7,11,Low,89.0
298,2db5db40-7365-4756-9bb7-29e3207a418d,Shanghai,Pune,China,India,Port of Shanghai,Port of Pune,13264.5,23,Low,58.0
299,c0aafcd0-b7c6-482e-a9d2-acf24c3eb138,Ho Chi Minh City,Ahmedabad,Vietnam,India,Port of Ho Chi Minh City,Port of Ahmedabad,12397.2,13,Medium,94.0

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df5.describe()

        distance_km  average_transit_days  traffic_index
count    300.000000            300.000000     291.000000
mean    6996.766333             15.156667      51.786942
std     4030.600619              8.651877      29.252338
min       89.100000              1.000000       1.000000
25%     3336.525000              7.000000      27.500000
50%     6893.950000             16.000000      53.000000
75%    10673.225000             22.000000      76.500000
max    13993.800000             30.000000     100.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df5.isnull().sum()

route_id                0
origin_city             0
destination_city        0
origin_country          0
destination_country     0
origin_port             0
destination_port        0
distance_km             0
average_transit_days    0
route_risk              6
traffic_index           9
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df5.isnull().sum()/len(df1))*100

route_id                 0.0
origin_city              0.0
destination_city         0.0
origin_country           0.0
destination_country      0.0
origin_port              0.0
destination_port         0.0
distance_km              0.0
average_transit_days     0.0
route_risk              20.0
traffic_index           30.0
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df5.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df5.nunique()

route_id                300
origin_city              36
destination_city         36
origin_country           22
destination_country      22
origin_port              36
destination_port         36
distance_km             300
average_transit_days     30
route_risk                3
traffic_index            98
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df5.sample(5, random_state=42)

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
203,a1f91fe4-c193-46c0-a6d8-c0fbb9d522e4,Bangkok,Vancouver,Thailand,Canada,Port of Bangkok,Port of Vancouver,13581.4,23,Medium,76.0
266,9607add6-6060-4334-9f8c-17dc4e9587d5,Singapore,Ahmedabad,Singapore,India,Port of Singapore,Port of Ahmedabad,10166.4,17,Medium,87.0
152,24854568-36c7-474c-9be3-54f86f1c1cf8,Shenzhen,Rio de Janeiro,China,Brazil,Port of Shenzhen,Port of Rio de Janeiro,1225.2,21,Medium,73.0
9,1ab72711-95d3-4895-a557-72a534378def,New York,Melbourne,USA,Australia,Port of New York,Port of Melbourne,7961.2,21,Low,52.0
233,54736b79-db3a-4b3e-9013-fa3e8bc9e483,Mumbai,Bangkok,India,Thailand,Port of Mumbai,Port of Bangkok,2969.0,17,Low,6.0

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df5.memory_usage(deep=True)

print("Total Memory Usage:", round(df2.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 334.57 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The routes.csv dataset contains information about transportation routes used for delivering shipments. Each record represents a unique route and includes details such as the origin location, destination location, travel distance, estimated transit time, traffic conditions, and route risk level. This dataset is connected to the shipments.csv dataset through the route_id field. Route characteristics have a significant impact on delivery performance, as longer distances, heavy traffic, and high-risk routes can increase shipment delays. Therefore, this dataset provides important operational features that can improve the accuracy of a shipment delay prediction model.

##Important Information about routes.csv

| Attribute           | Description                                                           |
| ------------------- | --------------------------------------------------------------------- |
| **Dataset Name**    | routes.csv                                                            |
| **DataFrame**       | df5                                                                   |
| **Dataset Type**    | Master Dataset                                                        |
| **Primary Key**     | route_id                                                              |
| **Related Dataset** | shipments.csv                                                         |
| **Relationship**    | One Route → Many Shipments                                            |
| **Purpose**         | Stores transportation route information used during shipment delivery |

##Useful Features for Delay Prediction

1.Origin City

2.Destination City

3.Origin Country

4.Destination Country

5.Distance (km)

6.Average Transit Days

7.Route Risk

8.Traffic Index
##Features Not Used Directly

1.Route ID (used only for joining datasets)

##Dataset Overview - routes.csv (df5)

In [ ]:
df5.shape

print("Number of Rows :", df5.shape[0])
print("Number of Columns :", df5.shape[1])

Number of Rows : 300
Number of Columns : 11

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df5.columns

Index(['route_id', 'origin_city', 'destination_city', 'origin_country',
       'destination_country', 'origin_port', 'destination_port', 'distance_km',
       'average_transit_days', 'route_risk', 'traffic_index'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df5.dtypes

route_id                 object
origin_city              object
destination_city         object
origin_country           object
destination_country      object
origin_port              object
destination_port         object
distance_km             float64
average_transit_days      int64
route_risk               object
traffic_index           float64
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   route_id              300 non-null    object
 1   origin_city           300 non-null    object
 2   destination_city      300 non-null    object
 3   origin_country        300 non-null    object
 4   destination_country   300 non-null    object
 5   origin_port           300 non-null    object
 6   destination_port      300 non-null    object
 7   distance_km           300 non-null    float64
 8   average_transit_days  300 non-null    int64
 9   route_risk            294 non-null    object
 10  traffic_index         291 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 25.9+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df5.head()

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
0,9e78f107-814c-477e-9d1f-45f98e13055d,Jeddah,Chicago,Saudi Arabia,USA,Port of Jeddah,Port of Chicago,12023.7,17,Low,99.0
1,53dfd4ec-4ed2-41fa-ab72-e023d823a48b,Ho Chi Minh City,Antwerp,Vietnam,Belgium,Port of Ho Chi Minh City,Port of Antwerp,13967.0,15,Medium,63.0
2,fb541cb9-674f-4ace-a42f-d329f4695f5e,Bengaluru,Chicago,India,USA,Port of Bengaluru,Port of Chicago,3441.6,7,High,42.0
3,6a1da14d-b39f-4fd7-82ac-0eab1209299f,Antwerp,Ahmedabad,Belgium,India,Port of Antwerp,Port of Ahmedabad,641.7,6,High,99.0
4,f01765d1-46b8-4301-ae38-c3d463322c21,Jeddah,Mumbai,Saudi Arabia,India,Port of Jeddah,Port of Mumbai,5803.8,7,Medium,NaN

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df5.tail()

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
295,9962d450-44ea-4af9-ad26-3459d7875481,Jeddah,Singapore,Saudi Arabia,Singapore,Port of Jeddah,Port of Singapore,9524.7,11,Low,58.0
296,fe29039e-5f23-4576-b1f6-6e539620aae3,Delhi,Shenzhen,India,China,Port of Delhi,Port of Shenzhen,4500.3,29,Low,92.0
297,22c1a25e-190d-488d-8117-fd1f76720e05,Hong Kong,Rio de Janeiro,China,Brazil,Port of Hong Kong,Port of Rio de Janeiro,11885.7,11,Low,89.0
298,2db5db40-7365-4756-9bb7-29e3207a418d,Shanghai,Pune,China,India,Port of Shanghai,Port of Pune,13264.5,23,Low,58.0
299,c0aafcd0-b7c6-482e-a9d2-acf24c3eb138,Ho Chi Minh City,Ahmedabad,Vietnam,India,Port of Ho Chi Minh City,Port of Ahmedabad,12397.2,13,Medium,94.0

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df5.describe()

        distance_km  average_transit_days  traffic_index
count    300.000000            300.000000     291.000000
mean    6996.766333             15.156667      51.786942
std     4030.600619              8.651877      29.252338
min       89.100000              1.000000       1.000000
25%     3336.525000              7.000000      27.500000
50%     6893.950000             16.000000      53.000000
75%    10673.225000             22.000000      76.500000
max    13993.800000             30.000000     100.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df5.isnull().sum()

route_id                0
origin_city             0
destination_city        0
origin_country          0
destination_country     0
origin_port             0
destination_port        0
distance_km             0
average_transit_days    0
route_risk              6
traffic_index           9
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df5.isnull().sum()/len(df1))*100

route_id                 0.0
origin_city              0.0
destination_city         0.0
origin_country           0.0
destination_country      0.0
origin_port              0.0
destination_port         0.0
distance_km              0.0
average_transit_days     0.0
route_risk              20.0
traffic_index           30.0
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df5.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df5.nunique()

route_id                300
origin_city              36
destination_city         36
origin_country           22
destination_country      22
origin_port              36
destination_port         36
distance_km             300
average_transit_days     30
route_risk                3
traffic_index            98
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df5.sample(5, random_state=42)

,route_id,origin_city,destination_city,origin_country,destination_country,origin_port,destination_port,distance_km,average_transit_days,route_risk,traffic_index
203,a1f91fe4-c193-46c0-a6d8-c0fbb9d522e4,Bangkok,Vancouver,Thailand,Canada,Port of Bangkok,Port of Vancouver,13581.4,23,Medium,76.0
266,9607add6-6060-4334-9f8c-17dc4e9587d5,Singapore,Ahmedabad,Singapore,India,Port of Singapore,Port of Ahmedabad,10166.4,17,Medium,87.0
152,24854568-36c7-474c-9be3-54f86f1c1cf8,Shenzhen,Rio de Janeiro,China,Brazil,Port of Shenzhen,Port of Rio de Janeiro,1225.2,21,Medium,73.0
9,1ab72711-95d3-4895-a557-72a534378def,New York,Melbourne,USA,Australia,Port of New York,Port of Melbourne,7961.2,21,Low,52.0
233,54736b79-db3a-4b3e-9013-fa3e8bc9e483,Mumbai,Bangkok,India,Thailand,Port of Mumbai,Port of Bangkok,2969.0,17,Low,6.0

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df5.memory_usage(deep=True)

print("Total Memory Usage:", round(df2.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 334.57 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Dataset Overview - shipment_delivery_history.csv (df6)

In [ ]:
df6.shape

print("Number of Rows :", df6.shape[0])
print("Number of Columns :", df6.shape[1])

Number of Rows : 4020
Number of Columns : 5

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df6.columns

Index(['history_id', 'shipment_id', 'actual_delivery_date', 'delivery_status',
       'delivery_attempts'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df6.dtypes

history_id               object
shipment_id              object
actual_delivery_date     object
delivery_status          object
delivery_attempts       float64
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   history_id            4020 non-null   object
 1   shipment_id           4020 non-null   object
 2   actual_delivery_date  4020 non-null   object
 3   delivery_status       4020 non-null   object
 4   delivery_attempts     3942 non-null   float64
dtypes: float64(1), object(4)
memory usage: 157.2+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df6.head()

,history_id,shipment_id,actual_delivery_date,delivery_status,delivery_attempts
0,d945d0ad-965e-4f75-a076-ad3e6df04011,2fbc2ba7-78db-4cd4-abc4-8484f8e296c0,2023-09-15,Delivered,2.0
1,1efbf0f3-db41-447b-bc9f-da1197fe9b73,1881d036-771b-4eb6-ae7a-ac78f41dfd79,2024-06-23,Delivered,1.0
2,2a991dc6-0cc1-4b90-8ee7-32014f1a8572,db4bcd2c-d981-4b8a-b61c-83c6dae109d8,2023-11-28,Delivered,1.0
3,bfe64b48-6caf-435b-a4ca-b1b9eb69eb19,b0787b6f-8743-4765-a0e8-f0457edad4bf,2025-02-17,Delivered,2.0
4,3fbcabd9-087a-4e57-b42e-5cdddd2ad9f1,473f319b-162e-4a31-a597-a386128b876a,2023-07-30,Delivered,1.0

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:



df6.tail()

,history_id,shipment_id,actual_delivery_date,delivery_status,delivery_attempts
4015,8bacefae-32a9-4a46-a218-dce060aa8336,a7f3905a-d007-4163-996a-1d2189005f35,2023-04-16,Delivered,3.0
4016,3da49ce5-4414-4c0b-91d5-e5e7c537680e,1ceadeb5-a1a1-49f0-b077-945818042277,2025-04-04,Delivered,1.0
4017,bac185d7-feec-43ca-95f8-7dfce4889b3b,c332c94c-2aba-45f5-b057-ba5b7d124023,2024-04-04,Delivered,1.0
4018,2b5e17a5-ac67-4941-97b0-d9eadd08681c,c05fa440-4427-46a3-823b-718a4b945ff5,2023-12-09,Delivered,1.0
4019,5fefd64b-1e80-4c57-9078-b8ba9ce614a5,77e51905-5c75-41bc-823d-4ea2fab7f75f,2024-12-11,Delivered,1.0

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df6.describe()

       delivery_attempts
count        3942.000000
mean            1.235667
std             0.537379
min             1.000000
25%             1.000000
50%             1.000000
75%             1.000000
max             3.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df6.isnull().sum()

history_id               0
shipment_id              0
actual_delivery_date     0
delivery_status          0
delivery_attempts       78
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df6.isnull().sum()/len(df1))*100

history_id                0.0
shipment_id               0.0
actual_delivery_date      0.0
delivery_status           0.0
delivery_attempts       260.0
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df6.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df6.nunique()

history_id              4020
shipment_id             4020
actual_delivery_date     909
delivery_status            2
delivery_attempts          3
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df6.sample(5, random_state=42)

,history_id,shipment_id,actual_delivery_date,delivery_status,delivery_attempts
2981,4807673c-a47a-4808-b9b6-6bb0cacf60d9,691b6d7d-b75f-4067-8eb0-8a0572e56037,2023-04-23,Delivered,1.0
1204,2b9038e0-8fa6-4789-90fc-9e19c19b06f0,b72d9367-8038-42da-91e2-d30239414e26,2024-10-14,Delivered,2.0
2720,18136ec4-5a4b-4073-8106-0fd09ea2331b,743b05f5-89ee-4858-a1e8-3eb571cac128,2024-09-07,Delivered,3.0
1954,21d07ac5-9afb-4b93-8767-672b4d0d71d3,294169f4-826a-4263-87e6-73a3100780d3,2024-07-12,Delivered,3.0
1226,4b0c2ec7-4ff8-4bfc-ae3e-af8747d7c167,bc12d032-eb21-44e8-a7bf-0b981ebf2778,2024-07-30,Delivered,NaN

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df6.memory_usage(deep=True)

print("Total Memory Usage:", round(df6.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 1158.08 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The shipment_delivery_history.csv dataset contains the historical delivery records of shipments. Each row represents the final delivery outcome of a shipment, including information such as the actual delivery date, delivery status, and delivery attempts. This dataset is linked to the shipments.csv dataset through the shipment_id field. Since it contains the final delivery outcome, it is primarily used to evaluate shipment performance and to create the target variable for shipment delay prediction. Variables such as actual delivery date and delivery status should not be used as input features because they are only available after delivery and would introduce target leakage into the model.

##Important Information about shipment_delivery_history.csv

| Attribute           | Description                                                       |
| ------------------- | ----------------------------------------------------------------- |
| **Dataset Name**    | shipment_delivery_history.csv                                     |
| **DataFrame**       | df6                                                               |
| **Dataset Type**    | Transaction Dataset                                               |
| **Primary Key**     | history_id                                                        |
| **Foreign Key**     | shipment_id                                                       |
| **Related Dataset** | shipments.csv                                                     |
| **Relationship**    | One Shipment → One Delivery History Record                        |
| **Purpose**         | Stores final delivery outcomes and delivery history for shipments |

##Useful Features

###This dataset is mainly used for creating the target variable, such as:

1.Actual Delivery Date

2.Delivery Status

3.Delivery Attempts (optional for post-analysis only)

##Features Not Used Directly for Model Training

1.History ID

2.Shipment ID (used only for joining)

3.Actual Delivery Date (used only to calculate delay)

4.Delivery Status (used as target variable if predicting delayed vs. on-time deliveries)

5.Delivery Attempts (known only after delivery and may cause data leakage)

##Dataset Overview - shipments.csv (df7)

In [ ]:
df7.shape

print("Number of Rows :", df7.shape[0])
print("Number of Columns :", df7.shape[1])

Number of Rows : 4060
Number of Columns : 21

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df7.columns

Index(['shipment_id', 'booking_id', 'customer_id', 'product_id', 'carrier_id',
       'warehouse_id', 'route_id', 'vehicle_id', 'customs_id', 'weather_id',
       'booking_date', 'ship_date', 'expected_delivery_date', 'shipping_mode',
       'shipment_type', 'priority', 'weight_kg', 'volume_cbm',
       'declared_value', 'insurance', 'fragile'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df7.dtypes

shipment_id                object
booking_id                 object
customer_id                object
product_id                 object
carrier_id                 object
warehouse_id               object
route_id                   object
vehicle_id                 object
customs_id                 object
weather_id                 object
booking_date               object
ship_date                  object
expected_delivery_date     object
shipping_mode              object
shipment_type              object
priority                   object
weight_kg                 float64
volume_cbm                float64
declared_value            float64
insurance                    bool
fragile                      bool
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4060 entries, 0 to 4059
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4060 non-null   object
 1   booking_id              4060 non-null   object
 2   customer_id             4060 non-null   object
 3   product_id              4060 non-null   object
 4   carrier_id              4060 non-null   object
 5   warehouse_id            4060 non-null   object
 6   route_id                4060 non-null   object
 7   vehicle_id              4060 non-null   object
 8   customs_id              4060 non-null   object
 9   weather_id              4060 non-null   object
 10  booking_date            4060 non-null   object
 11  ship_date               4060 non-null   object
 12  expected_delivery_date  4060 non-null   object
 13  shipping_mode           4060 non-null   object
 14  shipment_type           4060 non-null   object
 15  priority                3977 non-null   object
 16  weight_kg               4060 non-null   float64
 17  volume_cbm              3972 non-null   float64
 18  declared_value          3941 non-null   float64
 19  insurance               4060 non-null   bool
 20  fragile                 4060 non-null   bool
dtypes: bool(2), float64(3), object(16)
memory usage: 610.7+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df7.head()

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,ship_date,expected_delivery_date,shipping_mode,shipment_type,priority,weight_kg,volume_cbm,declared_value,insurance,fragile
0,2fbc2ba7-78db-4cd4-abc4-8484f8e296c0,BK100000,9d07a288-d20c-4632-be32-a80646174f82,7d9bcdf2-1cf5-4fdd-ba64-30b5ab5770fe,1b55fff6-046a-4456-9cb0-b8cd21addf5a,c8447ce1-fe0b-4d5b-96c9-b9a275ad8a25,aa747821-06b3-495f-b000-1b2e8b911707,f5ca04c7-97ce-4489-bfc9-69bb578f9273,de1b0e23-43fb-4d0d-a84a-07337bbc6411,a79111db-721a-4600-b313-ae9ab7f6f924,...,2023-08-13,2023-09-12,Sea,Import,Standard,40.6,0.12,8237.48,False,False
1,1881d036-771b-4eb6-ae7a-ac78f41dfd79,BK100001,189fab37-8b05-4e69-b000-be0f6ec9dbc4,5d909ac1-2fad-4861-a19e-79e99e125dfe,2a4ec8f6-16fe-4936-ac67-37fc52238e51,632799e1-4e31-4ba3-838e-c12663328395,1a5d3872-1ddf-4ff8-93e7-07fc5acafc25,830c2f7a-afba-4df9-b8b9-b5e5e1489cee,1d81cb99-8755-4f4a-bc2e-1bb414bbbe42,db916c48-9524-4904-b0d0-6016baeb0a3c,...,2024-06-17,2024-06-22,Rail,Export,Standard,57.1,0.22,7133.89,True,False
2,db4bcd2c-d981-4b8a-b61c-83c6dae109d8,BK100002,32320649-068b-4887-b776-ab2d9941cb1a,b1eb6a65-e462-4da5-a91f-78d00b0c241f,22c1d43a-dc69-48e3-8df1-18788f0cc19a,931ea697-c860-4af1-a6c8-e86f72c220ba,ddfeb7c4-87b1-4916-b523-22df1f1c16f3,a33fbf71-6b09-4246-921e-dd0de3c4600f,7e7b4406-6108-4603-897f-0f852c9f8927,6afe8d32-c11d-453f-9ca2-482ccc2e029d,...,2023-11-27,2023-11-28,Sea,Export,Standard,19.3,0.06,1813.83,False,True
3,b0787b6f-8743-4765-a0e8-f0457edad4bf,BK100003,f9670081-1287-4dca-9d8c-4beffacc6dcc,02c94f60-6dc8-4db8-94db-866ee6e7e608,28d939e1-9282-48ee-9a14-a7290d7e0350,a73aac58-381d-4494-84d2-de0456a1c93b,707f01ba-3ee5-4157-9845-41835b01dd03,55e1305e-cd49-4476-8b90-0ab1b3ef5e95,f7b4e378-7c54-45c1-8301-6911110a9b7e,895d6d8c-25b6-4dba-bf31-31f247df1d14,...,2025-01-17,2025-02-14,Air,Export,Standard,90.5,NaN,12633.50,True,False
4,473f319b-162e-4a31-a597-a386128b876a,BK100004,d7588951-ab24-43e4-87e7-78cf554e0eb1,a6a78e7a-331b-4e49-9a44-3040e0b2d655,75eda72c-e34b-40aa-b112-e56562058a14,57364895-d2f2-4a7e-9cd0-c2a5050d5b10,2db5db40-7365-4756-9bb7-29e3207a418d,7df258b3-189f-499d-b532-f6a016a22897,5b115244-608a-4e96-98a7-92f5acff7b54,9d00c1dc-afb4-4f76-8588-9c294802aa3c,...,2023-07-07,2023-07-30,Sea,Import,Express,745.0,3.95,178071.57,False,False

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df7.tail()

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,ship_date,expected_delivery_date,shipping_mode,shipment_type,priority,weight_kg,volume_cbm,declared_value,insurance,fragile
4055,a7f3905a-d007-4163-996a-1d2189005f35,BK100879,3b2a4d44-a5f3-4a24-85de-433f3499ad26,eed4d7c6-cb67-4add-aa84-26c7ef19422e,aabfdc24-e492-4483-a2cc-ca4e47359860,783f84e5-d8c9-48fa-b3b0-f0cc171a9a14,bc7d0585-afbd-474c-a550-a84c12880b09,655022ff-e41b-4aae-90fc-1349b37c3a88,e5f4e9bd-a00d-4674-b0e5-e83c98f93e8c,bf3fc9c4-9026-4664-9b89-70b74556880b,...,2023-04-07,2023-04-09,Road,Import,Standard,233.8,0.81,23208.83,True,False
4056,1ceadeb5-a1a1-49f0-b077-945818042277,BK102230,25f231a5-7cc6-477f-bbac-46f86a7db9b0,d6197749-8b78-4a94-8604-67e13c4053d1,bebdea49-529d-421e-8d97-7a4698581b23,7e29426d-c596-4850-9e23-7275fb5bd2dd,6487f266-3d75-46a4-9fab-474cded00c3c,9b868b58-4b2c-49cc-9c12-4f58ea6494de,5d6226df-0185-4d0e-8e3f-2228cd859f93,a5915d20-f5ce-4ac8-8884-28855e27c5e1,...,2025-03-05,2025-04-04,Road,Import,Standard,256.0,0.82,58173.54,False,False
4057,c332c94c-2aba-45f5-b057-ba5b7d124023,BK101411,3a5f16ba-6a22-4b73-8b42-f73a731a3d47,243c3401-91f2-4230-bda0-2ab25e7c6c5d,cc0432a0-2aa4-4753-ba02-535bcd0c99a6,253629ac-11f6-4a9d-9386-ddbb18cec8bf,2f72acb2-96f9-4711-8861-bcdc723b1eef,d1dfd78e-5557-49d6-bbb0-1324183bea04,e7b7ed9e-c302-4900-95e5-58c4d35cd999,d71bf22b-bd69-47b7-9e39-0f248dbb40d5,...,2024-03-31,2024-04-04,Air,Import,Express,763.8,2.17,84758.88,False,True
4058,c05fa440-4427-46a3-823b-718a4b945ff5,BK103224,8309725c-0a5c-460f-b553-07cf3d9f45c2,2c054104-1524-4ce7-afe7-401472832930,9724bcb8-902f-4bd0-984c-62b0dda845bc,93493494-acc7-4cc8-8663-22e503ac9836,ba992640-cfb3-4e29-9ea5-3e047f48f65d,5bda03b6-463b-4a86-9446-23eef8a696a5,fdd93703-f27e-423f-8b0a-824f6713d42a,41dcd8a1-f6c1-40b2-9137-8008150ca551,...,2023-12-03,2023-12-08,Road,Import,Express,20.4,0.10,NaN,True,False
4059,77e51905-5c75-41bc-823d-4ea2fab7f75f,BK103936,b975de83-1d69-40f6-ba3b-ad9401eb018f,8b5743f6-530f-4f50-8ce0-dcceaadcbbb6,22c1d43a-dc69-48e3-8df1-18788f0cc19a,57364895-d2f2-4a7e-9cd0-c2a5050d5b10,f91e4aa3-9234-4bd3-9f92-e4657a6f19c9,c375443f-289a-4382-94ae-bb131cbe4ac3,5496a2be-7830-433a-8c72-ec39e0ce92cd,7c36ee72-f960-461c-a597-28831270ac0d,...,2024-11-13,2024-12-07,Road,Export,Express,1014.0,4.02,111440.02,True,False

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df7.describe()

         weight_kg   volume_cbm  declared_value
count  4060.000000  3972.000000     3941.000000
mean    309.807094     1.222880    39892.919630
std     307.922457     1.324473    51424.828653
min       5.000000     0.010000       40.660000
25%      94.375000     0.350000     7558.730000
50%     217.500000     0.820000    22421.100000
75%     418.375000     1.622500    51672.200000
max    2771.000000    14.480000   579183.010000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df7.isnull().sum()

shipment_id                 0
booking_id                  0
customer_id                 0
product_id                  0
carrier_id                  0
warehouse_id                0
route_id                    0
vehicle_id                  0
customs_id                  0
weather_id                  0
booking_date                0
ship_date                   0
expected_delivery_date      0
shipping_mode               0
shipment_type               0
priority                   83
weight_kg                   0
volume_cbm                 88
declared_value            119
insurance                   0
fragile                     0
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df7.isnull().sum()/len(df1))*100

shipment_id                 0.000000
booking_id                  0.000000
customer_id                 0.000000
product_id                  0.000000
carrier_id                  0.000000
warehouse_id                0.000000
route_id                    0.000000
vehicle_id                  0.000000
customs_id                  0.000000
weather_id                  0.000000
booking_date                0.000000
ship_date                   0.000000
expected_delivery_date      0.000000
shipping_mode               0.000000
shipment_type               0.000000
priority                  276.666667
weight_kg                   0.000000
volume_cbm                293.333333
declared_value            396.666667
insurance                   0.000000
fragile                     0.000000
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df7.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df7.nunique()

shipment_id               4060
booking_id                4000
customer_id                623
product_id                 164
carrier_id                  30
warehouse_id                50
route_id                   300
vehicle_id                 300
customs_id                1617
weather_id                1158
booking_date               890
ship_date                  887
expected_delivery_date     912
shipping_mode                4
shipment_type                2
priority                     3
weight_kg                 2992
volume_cbm                 507
declared_value            3884
insurance                    2
fragile                      2
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df7.sample(5, random_state=42)

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,ship_date,expected_delivery_date,shipping_mode,shipment_type,priority,weight_kg,volume_cbm,declared_value,insurance,fragile
3285,c48a7b82-cd0e-4db8-93c0-c3eb6be53720,BK103285,72bc0b27-e988-43f1-bd5c-a0a6ef4bdf32,083a3283-7618-43e7-8127-4693b70910c0,cc0432a0-2aa4-4753-ba02-535bcd0c99a6,3124e1a4-58cb-4faa-b1d3-bec1a68b874b,c0bf27e3-7ab6-49a2-a1d5-ff08864a1cdb,adc8018f-34a4-484b-8061-3c203bde9fc3,fd6f9be1-ce9a-4125-8cf1-d15016e6d094,dcf34b44-4a52-48ba-be21-fca73b36f48c,...,2025-05-10,2025-05-12,Sea,Import,Standard,44.8,0.14,3660.31,False,False
2718,81d9dcf6-7cd4-4820-9f15-45e518cdb74e,BK102718,72bc0b27-e988-43f1-bd5c-a0a6ef4bdf32,0f540009-b705-4a55-9151-7910854dfe98,1b55fff6-046a-4456-9cb0-b8cd21addf5a,12c1108c-cd65-4726-b7f9-7c2cd4a2091b,7bbee08d-8931-4009-9c6b-aed0260f4d06,74eafe19-8ee1-4379-a213-39f212419939,6f9399df-1f9c-4fdf-a2e6-863b4c554d5e,ed886342-0bde-4689-800b-4098fd96ea41,...,2024-12-07,2024-12-19,Sea,Import,Standard,946.2,3.15,201111.39,False,False
4057,c332c94c-2aba-45f5-b057-ba5b7d124023,BK101411,3a5f16ba-6a22-4b73-8b42-f73a731a3d47,243c3401-91f2-4230-bda0-2ab25e7c6c5d,cc0432a0-2aa4-4753-ba02-535bcd0c99a6,253629ac-11f6-4a9d-9386-ddbb18cec8bf,2f72acb2-96f9-4711-8861-bcdc723b1eef,d1dfd78e-5557-49d6-bbb0-1324183bea04,e7b7ed9e-c302-4900-95e5-58c4d35cd999,d71bf22b-bd69-47b7-9e39-0f248dbb40d5,...,2024-03-31,2024-04-04,Air,Import,Express,763.8,2.17,84758.88,False,True
746,a52145f9-f18b-401b-bba6-78fa7e74ea32,BK100746,36c5201f-558d-442e-aca0-1e7903e9cccc,db01be78-0694-4061-99cb-8922fc6c148a,8ece1ccd-e714-4f7e-9cbe-ae2b70fbfe8e,dd959431-2350-425c-9ec4-8452a5e9234c,7f742b80-e9fe-4521-9b0a-4af11b7379bc,1c7ea6f9-936e-467a-85d9-1fe83e027bc1,23b60d9f-b315-497a-868c-6c7001ea999d,d0272cbf-fd2d-4626-a014-2d1617b9f69a,...,2024-08-20,2024-09-17,Road,Import,Standard,49.9,0.33,8633.43,False,True
1979,4b4392da-bf2b-4d05-be00-c60d9a9b523a,BK101979,03b0e610-c6ac-4f39-a1cc-32da6ebc4645,7d9bcdf2-1cf5-4fdd-ba64-30b5ab5770fe,f4a1d068-524c-4984-bf24-382f49c070be,f2eb93d7-650b-4988-8567-b740ffdd69be,a092155f-2340-4eac-9c58-7370847cd2da,5bfd04b0-1659-4d2d-b904-ac2a0c3e0f8e,359f17ad-1fd1-41df-a626-ec2fb49982e1,24ff15e4-b5ca-4551-bc2d-e61e2ed0597a,...,2024-07-10,2024-07-20,Rail,Export,Standard,754.3,1.93,137329.62,False,False

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df7.memory_usage(deep=True)

print("Total Memory Usage:", round(df7.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 4712.27 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The shipments.csv dataset is the primary dataset of this project and serves as the foundation for shipment delay prediction. Each record represents a shipment and contains references to customers, carriers, products, routes, warehouses, vehicles, customs, and weather conditions through their respective IDs. It also includes shipment-specific attributes such as shipping mode, shipment type, priority, package weight, volume, declared value, insurance status, and expected delivery date. This dataset integrates information from all other supporting datasets and provides the core features required for predictive modeling. Before model development, missing values, duplicate records, and data types should be carefully examined, and additional features may be engineered from date-related columns.

##Important Information about shipments.csv

| Attribute        | Description                                                             |
| ---------------- | ----------------------------------------------------------------------- |
| **Dataset Name** | shipments.csv                                                           |
| **DataFrame**    | df7                                                                     |
| **Dataset Type** | Main Transaction Dataset                                                |
| **Primary Key**  | shipment_id                                                             |
| **Purpose**      | Stores complete shipment information used for shipment delay prediction |
| **Importance**   | Central dataset that connects all other datasets                        |

##Most Important Features for Shipment Delay Prediction

1.Shipping Mode

2.Shipment Type

3.Shipment Priority

4.Package Weight

5.Shipment Volume

6.Declared Value

7.Insurance Status

8.Fragile Item Indicator

9.Booking Date

10.Ship Date

11.Expected Delivery Date

12.Customer ID (after merging with customer details)

13.Carrier ID (after merging with carrier details)

14.Route ID (after merging with route details)

15.Weather ID (after merging with weather information)

16.Vehicle ID (after merging with vehicle details)

17.Warehouse ID (after merging with warehouse details)
##Features Used Only for Joining

1.Shipment ID

2.Customer ID

3.Product ID

4.Carrier ID

5.Route ID

6.Vehicle ID

7.Warehouse ID

8.Customs ID

9.Weather ID

##Related Datasets

###The shipments.csv dataset is connected with:

customers.csv → customer_id

products.csv → product_id

carriers.csv → carrier_id

routes.csv → route_id

vehicles.csv → vehicle_id

warehouses.csv → warehouse_id

weather.csv → weather_id

customs.csv → customs_id

shipment_delivery_history.csv → shipment_id

##Dataset Overview - vehicles.csv (df8)

In [ ]:
df8.shape

print("Number of Rows :", df5.shape[0])
print("Number of Columns :", df5.shape[1])

Number of Rows : 300
Number of Columns : 11

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df8.columns

Index(['vehicle_id', 'vehicle_number', 'vehicle_type', 'capacity_kg',
       'fuel_type', 'maintenance_status', 'vehicle_age'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df8.dtypes

vehicle_id            object
vehicle_number        object
vehicle_type          object
capacity_kg            int64
fuel_type             object
maintenance_status    object
vehicle_age            int64
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          300 non-null    object
 1   vehicle_number      300 non-null    object
 2   vehicle_type        300 non-null    object
 3   capacity_kg         300 non-null    int64
 4   fuel_type           293 non-null    object
 5   maintenance_status  291 non-null    object
 6   vehicle_age         300 non-null    int64
dtypes: int64(2), object(5)
memory usage: 16.5+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df8.head()

,vehicle_id,vehicle_number,vehicle_type,capacity_kg,fuel_type,maintenance_status,vehicle_age
0,503f709e-75f9-41fd-be6b-1babec9a3302,UA-0067-KA,Aircraft,25317,Marine Fuel,Good,24
1,290d13af-045d-4e54-af2c-83645a3392a1,YG-7658-EY,Aircraft,22467,Marine Fuel,Due,4
2,2139f3fc-b192-472c-8ea0-1e4d5bb59e2b,EZ-9327-CS,Aircraft,9976,Petrol,Due,1
3,fdc3ac91-fdbd-48b4-8353-06b19104187f,EV-0541-KY,Wagon,20689,Electric,Due,14
4,830c2f7a-afba-4df9-b8b9-b5e5e1489cee,VM-2181-NE,Ship,12342,Diesel,Due,6

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df8.tail()

,vehicle_id,vehicle_number,vehicle_type,capacity_kg,fuel_type,maintenance_status,vehicle_age
295,c5d421d4-202c-4f89-8759-362a182b9f97,WM-2067-KG,Wagon,7895,Electric,Good,3
296,35e02879-74af-4235-be33-78a28680f7da,YZ-1364-JI,Aircraft,32993,Electric,Good,17
297,9f72dda8-ce2b-46d5-8bfc-9957502789ab,VD-5179-JZ,Truck,5890,Electric,Good,12
298,aaf1471d-3130-4883-9fb8-5782ed8b1d4e,BX-4168-SI,Ship,30446,Marine Fuel,Due,21
299,e29fdd8b-429b-4c8a-b253-c2b7f14120ce,FZ-2783-PK,Wagon,15302,Marine Fuel,Good,13

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df8.describe()

        capacity_kg  vehicle_age
count    300.000000   300.000000
mean   20563.953333    12.600000
std    11279.617954     7.539861
min      555.000000     0.000000
25%    10733.750000     6.000000
50%    20860.000000    13.000000
75%    30262.250000    19.250000
max    39939.000000    25.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df8.isnull().sum()

vehicle_id            0
vehicle_number        0
vehicle_type          0
capacity_kg           0
fuel_type             7
maintenance_status    9
vehicle_age           0
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df8.isnull().sum()/len(df1))*100

vehicle_id             0.000000
vehicle_number         0.000000
vehicle_type           0.000000
capacity_kg            0.000000
fuel_type             23.333333
maintenance_status    30.000000
vehicle_age            0.000000
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df8.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df8.nunique()

vehicle_id            300
vehicle_number        300
vehicle_type            4
capacity_kg           300
fuel_type               6
maintenance_status      3
vehicle_age            26
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df8.sample(5, random_state=42)

,vehicle_id,vehicle_number,vehicle_type,capacity_kg,fuel_type,maintenance_status,vehicle_age
203,9bb5f5f9-6515-43f3-98ae-02bb117d06a2,RS-4163-OZ,Aircraft,30599,Marine Fuel,Due,0
266,6aa90f87-5fc3-45a2-8c90-97db17bd42fa,KE-7498-HJ,Ship,11172,Marine Fuel,Good,10
152,8c26b903-cf8d-427e-81b0-f10b3e982623,GO-4110-BL,Ship,33247,Marine Fuel,Under Maintenance,25
9,8fc69a7b-1cf9-4904-b706-ee8f2e7d2533,MG-1497-BN,Aircraft,3705,Petrol,Good,20
233,9661e1c3-34e6-4870-9a17-c5820d4d873d,JF-1149-PY,Aircraft,13945,Marine Fuel,Good,21

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df8.memory_usage(deep=True)

print("Total Memory Usage:", round(df8.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 94.84 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The vehicles.csv dataset contains detailed information about the vehicles used for transporting shipments. Each record represents a unique vehicle and includes attributes such as vehicle type, carrying capacity, fuel type, maintenance status, and vehicle age. This dataset is linked to the shipments.csv dataset through the vehicle_id field. Vehicle characteristics directly influence transportation efficiency and delivery performance. Factors such as vehicle capacity, maintenance condition, and age can significantly impact shipment delays. Therefore, this dataset provides important operational features that can improve the performance of a shipment delay prediction model after preprocessing and integration.

##Important Information about vehicles.csv

| Attribute           | Description                                                 |
| ------------------- | ----------------------------------------------------------- |
| **Dataset Name**    | vehicles.csv                                                |
| **DataFrame**       | df8                                                         |
| **Dataset Type**    | Master Dataset                                              |
| **Primary Key**     | vehicle_id                                                  |
| **Related Dataset** | shipments.csv                                               |
| **Relationship**    | One Vehicle → Many Shipments                                |
| **Purpose**         | Stores vehicle information used for shipment transportation |

##Useful Features for Delay Prediction

1.Vehicle Type

2.Vehicle Capacity

3.Fuel Type

4.Maintenance Status

5.Vehicle Age

6.Availability Status (if available)

##Features Not Used Directly

1.Vehicle ID (used only for joining datasets)

2.Vehicle Registration Number (if present)

3.Driver Name (if present)

##Dataset Overview - warehouses.csv (df9)

In [ ]:
df9.shape

print("Number of Rows :", df9.shape[0])
print("Number of Columns :", df9.shape[1])

Number of Rows : 50
Number of Columns : 7

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df9.columns

Index(['warehouse_id', 'warehouse_name', 'city', 'state', 'warehouse_capacity',
       'current_utilization', 'warehouse_type'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df9.dtypes

warehouse_id            object
warehouse_name          object
city                    object
state                   object
warehouse_capacity     float64
current_utilization    float64
warehouse_type          object
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   warehouse_id         50 non-null     object
 1   warehouse_name       50 non-null     object
 2   city                 50 non-null     object
 3   state                50 non-null     object
 4   warehouse_capacity   50 non-null     float64
 5   current_utilization  48 non-null     float64
 6   warehouse_type       50 non-null     object
dtypes: float64(2), object(5)
memory usage: 2.9+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df9.head()

,warehouse_id,warehouse_name,city,state,warehouse_capacity,current_utilization,warehouse_type
0,95cb7f61-7030-488e-a21e-f25881fa9392,Istanbul Fulfillment Center,Istanbul,Istanbul,16503.0,52.6,Distribution
1,4e0a9685-3e0b-44a1-95d5-098f03a84068,Sao Paulo Regional Hub,Sao Paulo,Sao Paulo,4736.0,80.7,Regional
2,e692eb32-69c3-4aa2-aab7-8008643ca9ff,Mumbai Distribution Center,Mumbai,Maharashtra,12185.0,17.3,Distribution
3,c8688269-f520-41b9-a3c3-4eb7d3666cfc,Istanbul Distribution Center,Istanbul,Istanbul,18104.0,70.1,Regional
4,b09d1a21-0bc8-46ab-b707-d9c6c09981fd,Bengaluru Distribution Center,Bengaluru,Karnataka,6379.0,76.6,Regional

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df9.tail()

,warehouse_id,warehouse_name,city,state,warehouse_capacity,current_utilization,warehouse_type
45,a4867d58-a0f0-4818-a601-293f1e26b52f,Karachi Distribution Center,Karachi,Sindh,11848.0,60.2,Distribution
46,3e2e92a7-33ba-4679-b703-02bddd753301,Tokyo Distribution Center,Tokyo,Tokyo,18383.0,32.5,Regional
47,7e9e597b-833f-4a1b-bc64-dbfbe0c2931e,Pune Distribution Center,Pune,Maharashtra,12337.0,82.4,Regional
48,87e0260b-6980-422c-aff0-2cf55d9eead4,Hamburg Fulfillment Center,Hamburg,Hamburg,2306.0,57.3,Distribution
49,00b71ef8-acb3-4009-9050-e34379c33d39,Bangkok Distribution Center,Bangkok,Bangkok,4715.0,46.2,Distribution

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df9.describe()

       warehouse_capacity  current_utilization
count            50.00000            48.000000
mean          10589.58000            68.127083
std            5447.12689            19.733002
min            1142.00000            17.300000
25%            5771.00000            53.650000
50%           11141.50000            69.050000
75%           14445.00000            82.550000
max           19092.00000           100.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df9.isnull().sum()

warehouse_id           0
warehouse_name         0
city                   0
state                  0
warehouse_capacity     0
current_utilization    2
warehouse_type         0
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df9.isnull().sum()/len(df1))*100

warehouse_id           0.000000
warehouse_name         0.000000
city                   0.000000
state                  0.000000
warehouse_capacity     0.000000
current_utilization    6.666667
warehouse_type         0.000000
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df9.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df9.nunique()

warehouse_id           50
warehouse_name         40
city                   26
state                  24
warehouse_capacity     50
current_utilization    47
warehouse_type          2
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df9.sample(5, random_state=42)

,warehouse_id,warehouse_name,city,state,warehouse_capacity,current_utilization,warehouse_type
13,27330ffe-a496-48fd-acc2-0dcf47197492,Singapore Distribution Center,Singapore,Singapore,4393.0,83.0,Distribution
39,12c1108c-cd65-4726-b7f9-7c2cd4a2091b,Dubai Regional Hub,Dubai,Dubai,2308.0,71.2,Distribution
30,abd72f04-2444-4b67-9644-5e325f85b032,Chennai Distribution Center,Chennai,Tamil Nadu,13503.0,91.9,Distribution
45,a4867d58-a0f0-4818-a601-293f1e26b52f,Karachi Distribution Center,Karachi,Sindh,11848.0,60.2,Distribution
17,85c2e36a-13ee-467e-b56c-18a7d4df7114,Antwerp Fulfillment Center,Antwerp,Antwerp,10794.0,41.0,Distribution

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df9.memory_usage(deep=True)

print("Total Memory Usage:", round(df9.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 17.12 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The warehouses.csv dataset contains information about the warehouses involved in storing and dispatching shipments. Each record represents a unique warehouse and includes attributes such as warehouse location, warehouse type, storage capacity, and current utilization. This dataset is connected to the shipments.csv dataset through the warehouse_id field. Warehouse operations play a significant role in shipment efficiency because factors such as storage capacity, utilization level, and warehouse location can directly influence shipment processing and dispatch time. Therefore, this dataset provides important operational features that can improve the performance of a shipment delay prediction model after preprocessing and integration with the main shipment dataset.

##Important Information about warehouses.csv

| Attribute           | Description                                                                   |
| ------------------- | ----------------------------------------------------------------------------- |
| **Dataset Name**    | warehouses.csv                                                                |
| **DataFrame**       | df9                                                                           |
| **Dataset Type**    | Master Dataset                                                                |
| **Primary Key**     | warehouse_id                                                                  |
| **Related Dataset** | shipments.csv                                                                 |
| **Relationship**    | One Warehouse → Many Shipments                                                |
| **Purpose**         | Stores warehouse information used in shipment storage and dispatch operations |

##Useful Features for Delay Prediction

1.Warehouse Type

2.Warehouse Capacity

3.Current Utilization

4.Warehouse Location

5.City

6.State

7.Country

##Features Not Used Directly

1.Warehouse ID (used only for joining datasets)

2.Warehouse Name (if present)

3.Contact Details (if present)

##Dataset Overview - weather..csv (df10)

In [ ]:
df10.shape

print("Number of Rows :", df10.shape[0])
print("Number of Columns :", df10.shape[1])

Number of Rows : 1200
Number of Columns : 9

##**Interpretation** :



*   This cell displays the dimensions of the customers dataset.

*   The number of rows represents the total customer records, while the number of columns represents the attributes available for each customer.
*   Understanding the dataset size helps estimate the amount of information available for analysis.

In [ ]:
df10.columns

Index(['weather_id', 'city', 'forecast_date', 'weather_condition',
       'temperature', 'rainfall', 'humidity', 'wind_speed', 'visibility'],
      dtype='object')

##**Interpretation** :



*   This cell lists all the columns available in the dataset.
*   It helps identify customer-related attributes such as customer ID, customer type, industry, and location.
*   Reviewing the column names is the first step in understanding the structure of the dataset.

In [ ]:
df10.dtypes

weather_id            object
city                  object
forecast_date         object
weather_condition     object
temperature          float64
rainfall             float64
humidity             float64
wind_speed           float64
visibility           float64
dtype: object

##**Interpretation** :

*   This cell displays the data type of every column.
*   It helps distinguish between numerical and categorical variables.
*   Correct data types are important for statistical analysis and machine learning preprocessing.

In [ ]:
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   weather_id         1200 non-null   object
 1   city               1200 non-null   object
 2   forecast_date      1200 non-null   object
 3   weather_condition  1200 non-null   object
 4   temperature        1200 non-null   float64
 5   rainfall           1200 non-null   float64
 6   humidity           1174 non-null   float64
 7   wind_speed         1153 non-null   float64
 8   visibility         1133 non-null   float64
dtypes: float64(5), object(4)
memory usage: 84.5+ KB

##**Interpretation** :



*   This function provides a complete summary of the dataset.
*   It displays:

        *   Number of rows
        *   Number of non-null values
        *   Data types
        *   Memory usage
*   It also helps identify missing values and incorrect data types.

In [ ]:
df10.head()

,weather_id,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
0,7f327cfc-072b-47fd-81b5-08ed38e119d1,Hong Kong,2024-12-04,Fog,40.2,0.1,79.3,6.3,8.9
1,5aba2404-ccd6-4d6d-9ad9-71089bdfa0a3,Toronto,2025-10-19,Fog,18.8,0.2,35.6,1.5,9.2
2,65e3caca-a1f2-478d-94db-17517cb90694,Ho Chi Minh City,2026-01-18,Clear,7.0,0.1,80.8,3.3,9.8
3,ba11fa28-8f93-4833-8c95-a78d4623637e,Vancouver,2025-01-11,Rain,28.4,3.6,90.5,0.4,7.0
4,23708f5e-5275-4b0f-a800-e5bf89b698e7,Sydney,2024-08-31,Cloudy,14.2,0.1,79.5,20.1,NaN

##**Interpretation** :

*   Displays the first five customer records.
*   Helps verify that the dataset has been loaded correctly.
*   Provides a quick overview of the data structure.

In [ ]:
df10.tail()

,weather_id,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
1195,1243ce89-445c-417b-8e30-a17a5674754f,Melbourne,2025-03-26,Rain,-5.8,2.0,68.0,5.8,8.8
1196,da3567bb-69ec-4fc5-9024-a4de8ebb5557,Shenzhen,2025-04-17,Cloudy,-7.1,0.1,85.5,0.7,9.4
1197,50c68b8a-8d28-4e10-af3e-2a08a2c76235,Jakarta,2025-08-22,Storm,-5.2,7.2,48.9,14.2,2.0
1198,264b9a4b-f4a1-4da1-89ff-3babcef1b98a,Antwerp,2024-11-08,Clear,-6.6,0.1,30.2,3.0,8.1
1199,0b45dc62-119b-4e58-ba13-cfc7c15372a4,Cape Town,2025-02-22,Cloudy,20.6,0.5,72.5,7.5,7.6

##**Interpretation** :


*   Displays the last five records in the dataset.
*   Confirms that the dataset has been completely loaded.
*   Useful for checking the ending records for consistency.

In [ ]:
df10.describe()

       temperature     rainfall     humidity   wind_speed   visibility
count  1200.000000  1200.000000  1174.000000  1153.000000  1133.000000
mean     15.590000     1.296250    60.406474     8.003643     7.284554
std      14.680313     2.608435    22.463881     8.124203     2.084843
min     -10.000000     0.000000    20.000000     0.000000     0.600000
25%       2.600000     0.100000    41.500000     2.400000     6.500000
50%      15.350000     0.300000    60.050000     5.400000     7.700000
75%      27.750000     0.900000    79.475000    11.000000     8.800000
max      41.900000    19.900000   100.000000    63.200000    10.000000

##**Interpretation** :

This summarizes all numerical columns, including:

*   Count
*   Mean
*   Standard Deviation
*   Minimum
*   25th Percentile
*   Median (50%)
*   75th Percentile
*   Maximum

These statistics help understand the distribution of numerical features.

In [ ]:
df10.isnull().sum()

weather_id            0
city                  0
forecast_date         0
weather_condition     0
temperature           0
rainfall              0
humidity             26
wind_speed           47
visibility           67
dtype: int64

##**Interpretation** :

This identifies the number of missing values in each column. Missing values should be handled before building a machine learning model.

In [ ]:
(df10.isnull().sum()/len(df1))*100

weather_id             0.000000
city                   0.000000
forecast_date          0.000000
weather_condition      0.000000
temperature            0.000000
rainfall               0.000000
humidity              86.666667
wind_speed           156.666667
visibility           223.333333
dtype: float64

##**Interpretation** :

This shows the percentage of missing values in each column. Columns with a high percentage of missing values may require special treatment such as imputation or removal.

In [ ]:
df10.duplicated().sum()

np.int64(0)

##**Interpretation** :

Duplicate records can negatively affect data analysis and model performance. A value of 0 indicates there are no duplicate rows.

In [ ]:
df10.nunique()

weather_id           1200
city                   36
forecast_date         600
weather_condition       6
temperature           483
rainfall              105
humidity              620
wind_speed            261
visibility             91
dtype: int64

##**Interpretation** :

This shows how many distinct values are present in each column. It helps identify:


*   Identifier columns
*   Low-cardinality categorical features
*   Potential features for encoding

In [ ]:
df10.sample(5, random_state=42)

,weather_id,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
1178,c1664421-1adc-47ed-83f2-80b4a2317438,Kolkata,2026-06-11,Storm,11.2,1.7,81.1,1.5,3.8
865,2b53a077-6256-4b9a-8e70-748f167a5825,Hong Kong,2026-04-03,Rain,-3.6,10.5,56.3,10.6,7.5
101,c5a7a142-e1e5-42a6-bed6-88c7cf28b9c7,Melbourne,2025-04-24,Clear,4.2,0.4,24.1,0.4,7.5
439,7e0b7bb4-416b-495f-8dc2-09fc52f500cc,London,2025-09-20,Rain,0.5,12.8,69.1,2.4,6.3
58,859555f8-8ee8-41ff-bbb2-07ec6bf4ebfe,London,2025-04-29,Cloudy,28.4,0.0,51.0,2.7,7.2

##**Interpretation** :


*   Displays the number of unique values in each column
*   Useful for identifying:

          *   Primary *keys*
          *   Low-cardinality categorical variables
          *   High-cardinality columns
*   Helps in selecting suitable encoding techniques.

In [ ]:
df10.memory_usage(deep=True)

print("Total Memory Usage:", round(df10.memory_usage(deep=True).sum()/1024,2), "KB")

Total Memory Usage: 345.25 KB

##**Interpretation** :

*   Displays the memory consumed by each column.
*   Also calculates the total memory usage of the dataset.
*   Useful for evaluating storage requirements and optimizing memory usage for large datasets.

##Final Interpretation

The weather.csv dataset contains weather-related information associated with shipment transportation. Each record represents a specific weather condition and includes attributes such as temperature, humidity, rainfall, wind speed, visibility, and weather condition. This dataset is linked to the shipments.csv dataset through the weather_id field. Weather conditions play a significant role in transportation efficiency because adverse weather, such as heavy rainfall, storms, or poor visibility, can increase transit time and contribute to shipment delays. Therefore, this dataset provides valuable environmental features that can improve the performance of a shipment delay prediction model after preprocessing and integration with the main shipment dataset.

##Important Information about weather.csv

| Attribute           | Description                                                                                    |
| ------------------- | ---------------------------------------------------------------------------------------------- |
| **Dataset Name**    | weather.csv                                                                                    |
| **DataFrame**       | df10                                                                                           |
| **Dataset Type**    | Master Dataset                                                                                 |
| **Primary Key**     | weather_id                                                                                     |
| **Related Dataset** | shipments.csv                                                                                  |
| **Relationship**    | One Weather Record → Many Shipments                                                            |
| **Purpose**         | Stores weather information that may influence shipment transportation and delivery performance |

##Useful Features for Delay Prediction

1.Weather Condition

2.Temperature

3.Humidity

4.Rainfall

5.Wind Speed

6.Visibility

7.Atmospheric Pressure (if available)

##Fatures Not Used Directly

1.Weather ID (used only for joining datasets)

2.Weather Station Name (if present)

3.Observation ID (if present)