In [41]:
import pandas as pd
import numpy as np

In [42]:
df1 = pd.read_csv('/content/drive/MyDrive/DATA SET /carriers.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DATA SET /customers.csv')
df3 = pd.read_csv('/content/drive/MyDrive/DATA SET /customs.csv')
df4 = pd.read_csv('/content/drive/MyDrive/DATA SET /products.csv')
df5 = pd.read_csv('/content/drive/MyDrive/DATA SET /routes.csv')
df6 = pd.read_csv('/content/drive/MyDrive/DATA SET /shipment_delivery_history.csv')
df7 = pd.read_csv('/content/drive/MyDrive/DATA SET /shipments.csv')
df8 = pd.read_csv('/content/drive/MyDrive/DATA SET /vehicles.csv')
df9 = pd.read_csv('/content/drive/MyDrive/DATA SET /warehouses.csv')
df10 = pd.read_csv('/content/drive/MyDrive/DATA SET /weather.csv')

##Interpretation

This cell imports the required Python libraries, Pandas and NumPy, for data manipulation and analysis. It then loads the ten logistics-related CSV files into separate DataFrames (df1 to df10). Each dataset represents a different operational aspect of the logistics system, such as carriers, customers, products, routes, vehicles, warehouses, customs, weather conditions, shipment history, and shipments. Loading these datasets is the first step in preparing the data for integration and further preprocessing.

In [43]:
# Merge all datasets into one Master Dataset

master_df = (
    df7
    .merge(df1, on='carrier_id', how='inner')
    .merge(df2, on='customer_id', how='inner')
    .merge(df3, on='customs_id', how='inner')
    .merge(df4, on='product_id', how='inner')
    .merge(df5, on='route_id', how='inner')
    .merge(df6, on='shipment_id', how='inner')
    .merge(df8, on='vehicle_id', how='inner')
    .merge(df9, on='warehouse_id', how='inner')
    .merge(df10, on='weather_id', how='inner')
)

print("Master Dataset Shape:", master_df.shape)

master_df.head()

Master Dataset Shape: (4020, 83)

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,current_utilization,warehouse_type,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
0,2fbc2ba7-78db-4cd4-abc4-8484f8e296c0,BK100000,9d07a288-d20c-4632-be32-a80646174f82,7d9bcdf2-1cf5-4fdd-ba64-30b5ab5770fe,1b55fff6-046a-4456-9cb0-b8cd21addf5a,c8447ce1-fe0b-4d5b-96c9-b9a275ad8a25,aa747821-06b3-495f-b000-1b2e8b911707,f5ca04c7-97ce-4489-bfc9-69bb578f9273,de1b0e23-43fb-4d0d-a84a-07337bbc6411,a79111db-721a-4600-b313-ae9ab7f6f924,...,89.9,Regional,Sao Paulo,2025-08-09,Rain,27.9,0.1,36.4,5.3,9.5
1,1881d036-771b-4eb6-ae7a-ac78f41dfd79,BK100001,189fab37-8b05-4e69-b000-be0f6ec9dbc4,5d909ac1-2fad-4861-a19e-79e99e125dfe,2a4ec8f6-16fe-4936-ac67-37fc52238e51,632799e1-4e31-4ba3-838e-c12663328395,1a5d3872-1ddf-4ff8-93e7-07fc5acafc25,830c2f7a-afba-4df9-b8b9-b5e5e1489cee,1d81cb99-8755-4f4a-bc2e-1bb414bbbe42,db916c48-9524-4904-b0d0-6016baeb0a3c,...,88.5,Regional,Delhi,2026-07-14,Cloudy,31.2,0.0,51.9,1.5,7.0
2,db4bcd2c-d981-4b8a-b61c-83c6dae109d8,BK100002,32320649-068b-4887-b776-ab2d9941cb1a,b1eb6a65-e462-4da5-a91f-78d00b0c241f,22c1d43a-dc69-48e3-8df1-18788f0cc19a,931ea697-c860-4af1-a6c8-e86f72c220ba,ddfeb7c4-87b1-4916-b523-22df1f1c16f3,a33fbf71-6b09-4246-921e-dd0de3c4600f,7e7b4406-6108-4603-897f-0f852c9f8927,6afe8d32-c11d-453f-9ca2-482ccc2e029d,...,NaN,Distribution,Antwerp,2025-08-17,Clear,-5.2,0.2,38.5,1.6,9.2
3,b0787b6f-8743-4765-a0e8-f0457edad4bf,BK100003,f9670081-1287-4dca-9d8c-4beffacc6dcc,02c94f60-6dc8-4db8-94db-866ee6e7e608,28d939e1-9282-48ee-9a14-a7290d7e0350,a73aac58-381d-4494-84d2-de0456a1c93b,707f01ba-3ee5-4157-9845-41835b01dd03,55e1305e-cd49-4476-8b90-0ab1b3ef5e95,f7b4e378-7c54-45c1-8301-6911110a9b7e,895d6d8c-25b6-4dba-bf31-31f247df1d14,...,57.9,Regional,Kolkata,2026-02-13,Rain,41.6,0.5,25.8,16.9,7.2
4,473f319b-162e-4a31-a597-a386128b876a,BK100004,d7588951-ab24-43e4-87e7-78cf554e0eb1,a6a78e7a-331b-4e49-9a44-3040e0b2d655,75eda72c-e34b-40aa-b112-e56562058a14,57364895-d2f2-4a7e-9cd0-c2a5050d5b10,2db5db40-7365-4756-9bb7-29e3207a418d,7df258b3-189f-499d-b532-f6a016a22897,5b115244-608a-4e96-98a7-92f5acff7b54,9d00c1dc-afb4-4f76-8588-9c294802aa3c,...,94.7,Distribution,Dubai,2025-12-11,Fog,-7.3,0.0,83.6,5.2,1.7

##Interpretation

This cell combines all ten datasets into a single integrated dataset named master_df using Left Join operations. The shipments dataset (df7) serves as the primary table because it contains the foreign keys required to connect with all other datasets. Each related dataset is merged using its corresponding key (such as carrier_id, customer_id, product_id, and route_id). Using a Left Join ensures that all shipment records are preserved even if matching information is unavailable in the related tables. The resulting master dataset provides a comprehensive view of shipment operations and serves as the primary dataset for preprocessing, exploratory data analysis, feature engineering, and machine learning.

In [44]:
print("Rows :", master_df.shape[0])
print("Columns :", master_df.shape[1])

Rows : 4020
Columns : 83

In [45]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 83 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4020 non-null   object
 1   booking_id              4020 non-null   object
 2   customer_id             4020 non-null   object
 3   product_id              4020 non-null   object
 4   carrier_id              4020 non-null   object
 5   warehouse_id            4020 non-null   object
 6   route_id                4020 non-null   object
 7   vehicle_id              4020 non-null   object
 8   customs_id              4020 non-null   object
 9   weather_id              4020 non-null   object
 10  booking_date            4020 non-null   object
 11  ship_date               4020 non-null   object
 12  expected_delivery_date  4020 non-null   object
 13  shipping_mode           4020 non-null   object
 14  shipment_type           4020 non-null   object
 15  priority                3937 non-null   object
 16  weight_kg               4020 non-null   float64
 17  volume_cbm              3933 non-null   float64
 18  declared_value          3903 non-null   float64
 19  insurance               4020 non-null   bool
 20  fragile_x               4020 non-null   bool
 21  carrier_name            4020 non-null   object
 22  carrier_type            4020 non-null   object
 23  average_rating          4020 non-null   float64
 24  fleet_size              3768 non-null   float64
 25  years_of_service        4020 non-null   int64
 26  headquarters            4020 non-null   object
 27  customer_name           4020 non-null   object
 28  customer_type           3971 non-null   object
 29  industry                3790 non-null   object
 30  city_x                  4020 non-null   object
 31  state_x                 3918 non-null   object
 32  country                 4020 non-null   object
 33  registration_date       3974 non-null   object
 34  customer_status         4020 non-null   object
 35  customs_required        4020 non-null   bool
 36  documentation_complete  3947 non-null   object
 37  inspection_required     3892 non-null   object
 38  cargo_type              4020 non-null   object
 39  destination_country_x   4020 non-null   object
 40  product_name            4020 non-null   object
 41  category                4020 non-null   object
 42  hs_code                 3758 non-null   float64
 43  hazardous               4020 non-null   bool
 44  perishable              4020 non-null   bool
 45  temperature_controlled  4020 non-null   bool
 46  fragile_y               4020 non-null   bool
 47  weight_per_unit         3879 non-null   float64
 48  supplier_name           3775 non-null   object
 49  origin_city             4020 non-null   object
 50  destination_city        4020 non-null   object
 51  origin_country          4020 non-null   object
 52  destination_country_y   4020 non-null   object
 53  origin_port             4020 non-null   object
 54  destination_port        4020 non-null   object
 55  distance_km             4020 non-null   float64
 56  average_transit_days    4020 non-null   int64
 57  route_risk              3954 non-null   object
 58  traffic_index           3907 non-null   float64
 59  history_id              4020 non-null   object
 60  actual_delivery_date    4020 non-null   object
 61  delivery_status         4020 non-null   object
 62  delivery_attempts       3942 non-null   float64
 63  vehicle_number          4020 non-null   object
 64  vehicle_type            4020 non-null   object
 65  capacity_kg             4020 non-null   int64
 66  fuel_type               3940 non-null   object
 67  maintenance_status      3896 non-null   object
 68  vehicle_age             4020 non-null   int64
 69  warehouse_name          4020 non-null   object
 70  city_y                  4020 non-null   object
 71  state_y                 4020 non-null   object
 72  warehouse_capacity      4020 non-null   float64
 73  current_utilization     3854 non-null   float64
 74  warehouse_type          4020 non-null   object
 75  city                    4020 non-null   object
 76  forecast_date           4020 non-null   object
 77  weather_condition       4020 non-null   object
 78  temperature             4020 non-null   float64
 79  rainfall                4020 non-null   float64
 80  humidity                3937 non-null   float64
 81  wind_speed              3855 non-null   float64
 82  visibility              3788 non-null   float64
dtypes: bool(7), float64(17), int64(4), object(55)
memory usage: 2.4+ MB

In [46]:
missing = master_df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

hs_code                   262
fleet_size                252
supplier_name             245
visibility                232
industry                  230
current_utilization       166
wind_speed                165
weight_per_unit           141
inspection_required       128
maintenance_status        124
declared_value            117
traffic_index             113
state_x                   102
volume_cbm                 87
humidity                   83
priority                   83
fuel_type                  80
delivery_attempts          78
documentation_complete     73
route_risk                 66
customer_type              49
registration_date          46
dtype: int64

In [47]:
master_df['history_id'].isnull().sum()

np.int64(0)

In [48]:
master_df.isnull().sum().sum()

np.int64(2922)

In [49]:
master_df.duplicated().sum()

np.int64(0)

In [50]:
print(master_df.shape)

(4020, 83)

In [51]:
missing = master_df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

hs_code                   262
fleet_size                252
supplier_name             245
visibility                232
industry                  230
current_utilization       166
wind_speed                165
weight_per_unit           141
inspection_required       128
maintenance_status        124
declared_value            117
traffic_index             113
state_x                   102
volume_cbm                 87
humidity                   83
priority                   83
fuel_type                  80
delivery_attempts          78
documentation_complete     73
route_risk                 66
customer_type              49
registration_date          46
dtype: int64

In [52]:
# Create a copy of the merged dataset

df = master_df.copy()

print("Shape of Dataset:", df.shape)

df.head()

Shape of Dataset: (4020, 83)

,shipment_id,booking_id,customer_id,product_id,carrier_id,warehouse_id,route_id,vehicle_id,customs_id,weather_id,...,current_utilization,warehouse_type,city,forecast_date,weather_condition,temperature,rainfall,humidity,wind_speed,visibility
0,2fbc2ba7-78db-4cd4-abc4-8484f8e296c0,BK100000,9d07a288-d20c-4632-be32-a80646174f82,7d9bcdf2-1cf5-4fdd-ba64-30b5ab5770fe,1b55fff6-046a-4456-9cb0-b8cd21addf5a,c8447ce1-fe0b-4d5b-96c9-b9a275ad8a25,aa747821-06b3-495f-b000-1b2e8b911707,f5ca04c7-97ce-4489-bfc9-69bb578f9273,de1b0e23-43fb-4d0d-a84a-07337bbc6411,a79111db-721a-4600-b313-ae9ab7f6f924,...,89.9,Regional,Sao Paulo,2025-08-09,Rain,27.9,0.1,36.4,5.3,9.5
1,1881d036-771b-4eb6-ae7a-ac78f41dfd79,BK100001,189fab37-8b05-4e69-b000-be0f6ec9dbc4,5d909ac1-2fad-4861-a19e-79e99e125dfe,2a4ec8f6-16fe-4936-ac67-37fc52238e51,632799e1-4e31-4ba3-838e-c12663328395,1a5d3872-1ddf-4ff8-93e7-07fc5acafc25,830c2f7a-afba-4df9-b8b9-b5e5e1489cee,1d81cb99-8755-4f4a-bc2e-1bb414bbbe42,db916c48-9524-4904-b0d0-6016baeb0a3c,...,88.5,Regional,Delhi,2026-07-14,Cloudy,31.2,0.0,51.9,1.5,7.0
2,db4bcd2c-d981-4b8a-b61c-83c6dae109d8,BK100002,32320649-068b-4887-b776-ab2d9941cb1a,b1eb6a65-e462-4da5-a91f-78d00b0c241f,22c1d43a-dc69-48e3-8df1-18788f0cc19a,931ea697-c860-4af1-a6c8-e86f72c220ba,ddfeb7c4-87b1-4916-b523-22df1f1c16f3,a33fbf71-6b09-4246-921e-dd0de3c4600f,7e7b4406-6108-4603-897f-0f852c9f8927,6afe8d32-c11d-453f-9ca2-482ccc2e029d,...,NaN,Distribution,Antwerp,2025-08-17,Clear,-5.2,0.2,38.5,1.6,9.2
3,b0787b6f-8743-4765-a0e8-f0457edad4bf,BK100003,f9670081-1287-4dca-9d8c-4beffacc6dcc,02c94f60-6dc8-4db8-94db-866ee6e7e608,28d939e1-9282-48ee-9a14-a7290d7e0350,a73aac58-381d-4494-84d2-de0456a1c93b,707f01ba-3ee5-4157-9845-41835b01dd03,55e1305e-cd49-4476-8b90-0ab1b3ef5e95,f7b4e378-7c54-45c1-8301-6911110a9b7e,895d6d8c-25b6-4dba-bf31-31f247df1d14,...,57.9,Regional,Kolkata,2026-02-13,Rain,41.6,0.5,25.8,16.9,7.2
4,473f319b-162e-4a31-a597-a386128b876a,BK100004,d7588951-ab24-43e4-87e7-78cf554e0eb1,a6a78e7a-331b-4e49-9a44-3040e0b2d655,75eda72c-e34b-40aa-b112-e56562058a14,57364895-d2f2-4a7e-9cd0-c2a5050d5b10,2db5db40-7365-4756-9bb7-29e3207a418d,7df258b3-189f-499d-b532-f6a016a22897,5b115244-608a-4e96-98a7-92f5acff7b54,9d00c1dc-afb4-4f76-8588-9c294802aa3c,...,94.7,Distribution,Dubai,2025-12-11,Fog,-7.3,0.0,83.6,5.2,1.7

##Interpretation

This cell creates a copy of the merged dataset and stores it in a new DataFrame named df. Working on a copy protects the original merged dataset (master_df) from accidental modifications during preprocessing. All subsequent operations, including handling missing values, treating outliers, feature engineering, encoding, and scaling, will be performed on this copy. This is considered a best practice in data preprocessing because it preserves the original integrated dataset for future reference or comparison.

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 83 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4020 non-null   object
 1   booking_id              4020 non-null   object
 2   customer_id             4020 non-null   object
 3   product_id              4020 non-null   object
 4   carrier_id              4020 non-null   object
 5   warehouse_id            4020 non-null   object
 6   route_id                4020 non-null   object
 7   vehicle_id              4020 non-null   object
 8   customs_id              4020 non-null   object
 9   weather_id              4020 non-null   object
 10  booking_date            4020 non-null   object
 11  ship_date               4020 non-null   object
 12  expected_delivery_date  4020 non-null   object
 13  shipping_mode           4020 non-null   object
 14  shipment_type           4020 non-null   object
 15  priority                3937 non-null   object
 16  weight_kg               4020 non-null   float64
 17  volume_cbm              3933 non-null   float64
 18  declared_value          3903 non-null   float64
 19  insurance               4020 non-null   bool
 20  fragile_x               4020 non-null   bool
 21  carrier_name            4020 non-null   object
 22  carrier_type            4020 non-null   object
 23  average_rating          4020 non-null   float64
 24  fleet_size              3768 non-null   float64
 25  years_of_service        4020 non-null   int64
 26  headquarters            4020 non-null   object
 27  customer_name           4020 non-null   object
 28  customer_type           3971 non-null   object
 29  industry                3790 non-null   object
 30  city_x                  4020 non-null   object
 31  state_x                 3918 non-null   object
 32  country                 4020 non-null   object
 33  registration_date       3974 non-null   object
 34  customer_status         4020 non-null   object
 35  customs_required        4020 non-null   bool
 36  documentation_complete  3947 non-null   object
 37  inspection_required     3892 non-null   object
 38  cargo_type              4020 non-null   object
 39  destination_country_x   4020 non-null   object
 40  product_name            4020 non-null   object
 41  category                4020 non-null   object
 42  hs_code                 3758 non-null   float64
 43  hazardous               4020 non-null   bool
 44  perishable              4020 non-null   bool
 45  temperature_controlled  4020 non-null   bool
 46  fragile_y               4020 non-null   bool
 47  weight_per_unit         3879 non-null   float64
 48  supplier_name           3775 non-null   object
 49  origin_city             4020 non-null   object
 50  destination_city        4020 non-null   object
 51  origin_country          4020 non-null   object
 52  destination_country_y   4020 non-null   object
 53  origin_port             4020 non-null   object
 54  destination_port        4020 non-null   object
 55  distance_km             4020 non-null   float64
 56  average_transit_days    4020 non-null   int64
 57  route_risk              3954 non-null   object
 58  traffic_index           3907 non-null   float64
 59  history_id              4020 non-null   object
 60  actual_delivery_date    4020 non-null   object
 61  delivery_status         4020 non-null   object
 62  delivery_attempts       3942 non-null   float64
 63  vehicle_number          4020 non-null   object
 64  vehicle_type            4020 non-null   object
 65  capacity_kg             4020 non-null   int64
 66  fuel_type               3940 non-null   object
 67  maintenance_status      3896 non-null   object
 68  vehicle_age             4020 non-null   int64
 69  warehouse_name          4020 non-null   object
 70  city_y                  4020 non-null   object
 71  state_y                 4020 non-null   object
 72  warehouse_capacity      4020 non-null   float64
 73  current_utilization     3854 non-null   float64
 74  warehouse_type          4020 non-null   object
 75  city                    4020 non-null   object
 76  forecast_date           4020 non-null   object
 77  weather_condition       4020 non-null   object
 78  temperature             4020 non-null   float64
 79  rainfall                4020 non-null   float64
 80  humidity                3937 non-null   float64
 81  wind_speed              3855 non-null   float64
 82  visibility              3788 non-null   float64
dtypes: bool(7), float64(17), int64(4), object(55)
memory usage: 2.4+ MB

##Interpretation

This cell provides a comprehensive summary of the merged dataset. It displays the total number of rows and columns, the data type of each feature, the number of non-null values, and the overall memory usage. It also helps identify columns with missing values and verifies whether each column has the appropriate data type. This information is essential for planning the subsequent preprocessing steps, such as handling missing values, converting data types, and preparing the dataset for machine learning.

In [54]:
# Check duplicate rows

duplicates = df.duplicated().sum()

print("Duplicate Records:", duplicates)

Duplicate Records: 0

##Interpretation

This cell checks for duplicate records in the merged dataset by counting the number of identical rows. Duplicate records can introduce redundancy, bias statistical analysis, and negatively affect machine learning model performance. Identifying duplicates is an important preprocessing step to ensure data quality and maintain the integrity of the dataset before further analysis.

In [55]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

priority                   83
volume_cbm                 87
declared_value            117
fleet_size                252
customer_type              49
industry                  230
state_x                   102
registration_date          46
documentation_complete     73
inspection_required       128
hs_code                   262
weight_per_unit           141
supplier_name             245
route_risk                 66
traffic_index             113
delivery_attempts          78
fuel_type                  80
maintenance_status        124
current_utilization       166
humidity                   83
wind_speed                165
visibility                232
dtype: int64

##Interpretation

This cell identifies all columns that contain missing values and displays the total number of missing entries in each column. Missing values can reduce the accuracy of data analysis and machine learning models if not handled properly. By identifying only the affected columns, this step helps determine which features require appropriate imputation techniques during preprocessing.

In [56]:
missing_percent = (df.isnull().sum()/len(df))*100

missing_percent[missing_percent>0].sort_values(ascending=False)

hs_code                   6.517413
fleet_size                6.268657
supplier_name             6.094527
visibility                5.771144
industry                  5.721393
current_utilization       4.129353
wind_speed                4.104478
weight_per_unit           3.507463
inspection_required       3.184080
maintenance_status        3.084577
declared_value            2.910448
traffic_index             2.810945
state_x                   2.537313
volume_cbm                2.164179
humidity                  2.064677
priority                  2.064677
fuel_type                 1.990050
delivery_attempts         1.940299
documentation_complete    1.815920
route_risk                1.641791
customer_type             1.218905
registration_date         1.144279
dtype: float64

##Interpretation

This cell calculates the percentage of missing values for each column in the merged dataset and displays only those columns that contain missing data in descending order. Evaluating the percentage of missing values helps determine the most suitable preprocessing strategy. Columns with a low percentage of missing values can generally be imputed using statistical methods such as the median or mode, while columns with a high percentage of missing values may require more careful consideration. In this dataset, all missing-value percentages are relatively low, making imputation an appropriate approach without removing any columns or records.

In [57]:
# ================================
# Fill Missing Values
# ================================

# Numerical Columns (Fill with Median)
numerical_cols = [
    'fleet_size',
    'declared_value',
    'weight_per_unit',
    'traffic_index',
    'delivery_attempts',
    'current_utilization',
    'humidity',
    'wind_speed',
    'volume_cbm'
]

for col in numerical_cols:
    if col in df.columns:
        df[col].fillna(df[col].median(), inplace=True)

# Categorical Columns (Fill with Mode)
categorical_cols = [
    'priority',
    'customer_type',
    'industry',
    'state_x',
    'documentation_complete',
    'inspection_required',
    'hs_code',
    'supplier_name',
    'route_risk',
    'history_id',
    'delivery_status',
    'fuel_type',
    'maintenance_status',
    'visibility'
]

for col in categorical_cols:
    if col in df.columns:
        df[col].fillna(df[col].mode()[0], inplace=True)

# Date Columns (Fill with Most Frequent Date)
date_cols = [
    'registration_date',
    'actual_delivery_date'
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
        df[col].fillna(df[col].mode()[0], inplace=True)

print("✅ All missing values have been handled successfully.")

✅ All missing values have been handled successfully.

/tmp/ipykernel_678/2484255833.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_678/2484255833.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_678/2484255833.py:42: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_678/2484255833.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_678/2484255833.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

##Interpretation

This cell handles all missing values in the merged dataset using appropriate imputation techniques based on the data type of each feature. Missing values in numerical columns are replaced with the median, as it is less affected by outliers and preserves the overall distribution of the data. Missing values in categorical columns are filled with the mode (most frequently occurring value), ensuring data consistency while maintaining the most common category. Date columns are first converted into the datetime format and then any missing dates are replaced with the most frequently occurring date. This preprocessing step ensures that the dataset is complete and suitable for further analysis and machine learning without losing valuable records.

In [58]:
# Check Remaining Missing Values

remaining_missing = df.isnull().sum()

remaining_missing[remaining_missing > 0]

Series([], dtype: int64)

##Interpretation

This cell verifies whether any missing values still exist after the imputation process. It displays only those columns that contain missing values greater than zero. If the output is empty, it confirms that all missing values have been successfully handled. This validation step ensures that the dataset is complete and ready for the next stages of preprocessing.

In [59]:
df.isnull().sum()

shipment_id    0
booking_id     0
customer_id    0
product_id     0
carrier_id     0
              ..
temperature    0
rainfall       0
humidity       0
wind_speed     0
visibility     0
Length: 83, dtype: int64

##Interpretation

This cell performs a final verification by displaying the number of missing values for every column in the dataset. A value of 0 for all columns confirms that the missing value treatment has been successfully completed. The dataset is now free from missing data and is prepared for the subsequent preprocessing tasks, including outlier detection, feature engineering, categorical encoding, feature scaling, and machine learning model development.

##Final Interpretation



*   All missing values in the merged dataset have been successfully handled.
*   Numerical features were imputed using the median, while categorical features were filled using the mode.
*   Date columns were converted to datetime format and missing dates were appropriately imputed.
*   The dataset now contains no missing values, making it suitable for the next stages of preprocessing, including outlier detection, feature engineering, encoding, feature scaling, and machine learning model development.

In [60]:
# Save the cleaned and merged dataset

df.to_csv('/content/cleaned_merged_dataset.csv', index=False)

print("✅ Cleaned and Merged Dataset saved successfully.")

✅ Cleaned and Merged Dataset saved successfully.

##Interpretation

*   This cell saves the preprocessed merged dataset as a CSV file.
*   The saved file contains all merged information with missing values handled and is ready for further analysis.
*   This dataset can now be used directly for subsequent tasks without repeating the preprocessing steps.

In [62]:
df.shape

(4020, 83)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 83 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4020 non-null   object
 1   booking_id              4020 non-null   object
 2   customer_id             4020 non-null   object
 3   product_id              4020 non-null   object
 4   carrier_id              4020 non-null   object
 5   warehouse_id            4020 non-null   object
 6   route_id                4020 non-null   object
 7   vehicle_id              4020 non-null   object
 8   customs_id              4020 non-null   object
 9   weather_id              4020 non-null   object
 10  booking_date            4020 non-null   object
 11  ship_date               4020 non-null   object
 12  expected_delivery_date  4020 non-null   object
 13  shipping_mode           4020 non-null   object
 14  shipment_type           4020 non-null   object
 15  priority                4020 non-null   object
 16  weight_kg               4020 non-null   float64
 17  volume_cbm              4020 non-null   float64
 18  declared_value          4020 non-null   float64
 19  insurance               4020 non-null   bool
 20  fragile_x               4020 non-null   bool
 21  carrier_name            4020 non-null   object
 22  carrier_type            4020 non-null   object
 23  average_rating          4020 non-null   float64
 24  fleet_size              4020 non-null   float64
 25  years_of_service        4020 non-null   int64
 26  headquarters            4020 non-null   object
 27  customer_name           4020 non-null   object
 28  customer_type           4020 non-null   object
 29  industry                4020 non-null   object
 30  city_x                  4020 non-null   object
 31  state_x                 4020 non-null   object
 32  country                 4020 non-null   object
 33  registration_date       4020 non-null   datetime64[ns]
 34  customer_status         4020 non-null   object
 35  customs_required        4020 non-null   bool
 36  documentation_complete  4020 non-null   bool
 37  inspection_required     4020 non-null   bool
 38  cargo_type              4020 non-null   object
 39  destination_country_x   4020 non-null   object
 40  product_name            4020 non-null   object
 41  category                4020 non-null   object
 42  hs_code                 4020 non-null   float64
 43  hazardous               4020 non-null   bool
 44  perishable              4020 non-null   bool
 45  temperature_controlled  4020 non-null   bool
 46  fragile_y               4020 non-null   bool
 47  weight_per_unit         4020 non-null   float64
 48  supplier_name           4020 non-null   object
 49  origin_city             4020 non-null   object
 50  destination_city        4020 non-null   object
 51  origin_country          4020 non-null   object
 52  destination_country_y   4020 non-null   object
 53  origin_port             4020 non-null   object
 54  destination_port        4020 non-null   object
 55  distance_km             4020 non-null   float64
 56  average_transit_days    4020 non-null   int64
 57  route_risk              4020 non-null   object
 58  traffic_index           4020 non-null   float64
 59  history_id              4020 non-null   object
 60  actual_delivery_date    4020 non-null   datetime64[ns]
 61  delivery_status         4020 non-null   object
 62  delivery_attempts       4020 non-null   float64
 63  vehicle_number          4020 non-null   object
 64  vehicle_type            4020 non-null   object
 65  capacity_kg             4020 non-null   int64
 66  fuel_type               4020 non-null   object
 67  maintenance_status      4020 non-null   object
 68  vehicle_age             4020 non-null   int64
 69  warehouse_name          4020 non-null   object
 70  city_y                  4020 non-null   object
 71  state_y                 4020 non-null   object
 72  warehouse_capacity      4020 non-null   float64
 73  current_utilization     4020 non-null   float64
 74  warehouse_type          4020 non-null   object
 75  city                    4020 non-null   object
 76  forecast_date           4020 non-null   object
 77  weather_condition       4020 non-null   object
 78  temperature             4020 non-null   float64
 79  rainfall                4020 non-null   float64
 80  humidity                4020 non-null   float64
 81  wind_speed              4020 non-null   float64
 82  visibility              4020 non-null   float64
dtypes: bool(9), datetime64[ns](2), float64(17), int64(4), object(51)
memory usage: 2.3+ MB

In [64]:
# Convert object columns to datetime format

date_columns = [
    'booking_date',
    'ship_date',
    'expected_delivery_date',
    'forecast_date'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print("Date columns converted successfully.")

Date columns converted successfully.

In [65]:
# Verify the data types of date columns

df[date_columns].dtypes

booking_date              datetime64[ns]
ship_date                 datetime64[ns]
expected_delivery_date    datetime64[ns]
forecast_date             datetime64[ns]
dtype: object

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 83 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4020 non-null   object
 1   booking_id              4020 non-null   object
 2   customer_id             4020 non-null   object
 3   product_id              4020 non-null   object
 4   carrier_id              4020 non-null   object
 5   warehouse_id            4020 non-null   object
 6   route_id                4020 non-null   object
 7   vehicle_id              4020 non-null   object
 8   customs_id              4020 non-null   object
 9   weather_id              4020 non-null   object
 10  booking_date            4020 non-null   datetime64[ns]
 11  ship_date               4020 non-null   datetime64[ns]
 12  expected_delivery_date  4020 non-null   datetime64[ns]
 13  shipping_mode           4020 non-null   object
 14  shipment_type           4020 non-null   object
 15  priority                4020 non-null   object
 16  weight_kg               4020 non-null   float64
 17  volume_cbm              4020 non-null   float64
 18  declared_value          4020 non-null   float64
 19  insurance               4020 non-null   bool
 20  fragile_x               4020 non-null   bool
 21  carrier_name            4020 non-null   object
 22  carrier_type            4020 non-null   object
 23  average_rating          4020 non-null   float64
 24  fleet_size              4020 non-null   float64
 25  years_of_service        4020 non-null   int64
 26  headquarters            4020 non-null   object
 27  customer_name           4020 non-null   object
 28  customer_type           4020 non-null   object
 29  industry                4020 non-null   object
 30  city_x                  4020 non-null   object
 31  state_x                 4020 non-null   object
 32  country                 4020 non-null   object
 33  registration_date       4020 non-null   datetime64[ns]
 34  customer_status         4020 non-null   object
 35  customs_required        4020 non-null   bool
 36  documentation_complete  4020 non-null   bool
 37  inspection_required     4020 non-null   bool
 38  cargo_type              4020 non-null   object
 39  destination_country_x   4020 non-null   object
 40  product_name            4020 non-null   object
 41  category                4020 non-null   object
 42  hs_code                 4020 non-null   float64
 43  hazardous               4020 non-null   bool
 44  perishable              4020 non-null   bool
 45  temperature_controlled  4020 non-null   bool
 46  fragile_y               4020 non-null   bool
 47  weight_per_unit         4020 non-null   float64
 48  supplier_name           4020 non-null   object
 49  origin_city             4020 non-null   object
 50  destination_city        4020 non-null   object
 51  origin_country          4020 non-null   object
 52  destination_country_y   4020 non-null   object
 53  origin_port             4020 non-null   object
 54  destination_port        4020 non-null   object
 55  distance_km             4020 non-null   float64
 56  average_transit_days    4020 non-null   int64
 57  route_risk              4020 non-null   object
 58  traffic_index           4020 non-null   float64
 59  history_id              4020 non-null   object
 60  actual_delivery_date    4020 non-null   datetime64[ns]
 61  delivery_status         4020 non-null   object
 62  delivery_attempts       4020 non-null   float64
 63  vehicle_number          4020 non-null   object
 64  vehicle_type            4020 non-null   object
 65  capacity_kg             4020 non-null   int64
 66  fuel_type               4020 non-null   object
 67  maintenance_status      4020 non-null   object
 68  vehicle_age             4020 non-null   int64
 69  warehouse_name          4020 non-null   object
 70  city_y                  4020 non-null   object
 71  state_y                 4020 non-null   object
 72  warehouse_capacity      4020 non-null   float64
 73  current_utilization     4020 non-null   float64
 74  warehouse_type          4020 non-null   object
 75  city                    4020 non-null   object
 76  forecast_date           4020 non-null   datetime64[ns]
 77  weather_condition       4020 non-null   object
 78  temperature             4020 non-null   float64
 79  rainfall                4020 non-null   float64
 80  humidity                4020 non-null   float64
 81  wind_speed              4020 non-null   float64
 82  visibility              4020 non-null   float64
dtypes: bool(9), datetime64[ns](6), float64(17), int64(4), object(47)
memory usage: 2.3+ MB

In [67]:
# Check Date Columns

date_columns = [
    'booking_date',
    'ship_date',
    'expected_delivery_date',
    'registration_date',
    'actual_delivery_date',
    'forecast_date'
]

df[date_columns].dtypes

booking_date              datetime64[ns]
ship_date                 datetime64[ns]
expected_delivery_date    datetime64[ns]
registration_date         datetime64[ns]
actual_delivery_date      datetime64[ns]
forecast_date             datetime64[ns]
dtype: object

##Interpretation

This cell verifies that all date-related columns have been successfully converted to the datetime data type. Correct date formatting is essential for performing accurate time-based calculations and feature engineering.

In [68]:
# ============================================
# Feature Engineering
# ============================================

# Calculate Shipment Delay (in days)

df['shipment_delay'] = (
    df['actual_delivery_date'] -
    df['expected_delivery_date']
).dt.days

df[['actual_delivery_date',
    'expected_delivery_date',
    'shipment_delay']].head()

  actual_delivery_date expected_delivery_date  shipment_delay
0           2023-09-15             2023-09-12               3
1           2024-06-23             2024-06-22               1
2           2023-11-28             2023-11-28               0
3           2025-02-17             2025-02-14               3
4           2023-07-30             2023-07-30               0

##Interpretation

This cell calculates the shipment delay by computing the difference between the actual delivery date and the expected delivery date. Positive values indicate late deliveries, negative values indicate early deliveries, and zero represents on-time deliveries. This feature forms the basis for shipment delay analysis.

In [69]:
# Create Delay Days
# Negative values become zero

df['delay_days'] = df['shipment_delay'].clip(lower=0)

df[['shipment_delay','delay_days']].head()

   shipment_delay  delay_days
0               3           3
1               1           1
2               0           0
3               3           3
4               0           0

##Interpretation

This cell creates a new feature called delay_days, which represents only the number of delayed days. Early deliveries are converted to zero because they do not contribute to shipment delays. This feature provides a more meaningful business measure for analyzing late deliveries.

In [70]:
# Create Binary Target Variable

df['shipment_delayed'] = (df['delay_days'] > 0).astype(int)

df[['delay_days','shipment_delayed']].head()

   delay_days  shipment_delayed
0           3                 1
1           1                 1
2           0                 0
3           3                 1
4           0                 0

##Interpretation

This cell creates the binary target variable shipment_delayed. A value of 1 indicates that a shipment was delivered late, while 0 represents shipments delivered on time or earlier. This target variable is appropriate for building a shipment delay prediction model using classification algorithms.

In [71]:
print(df[['shipment_delay',
          'delay_days',
          'shipment_delayed']].describe())

print("\n")

print(df['shipment_delayed'].value_counts())

       shipment_delay   delay_days  shipment_delayed
count     4020.000000  4020.000000       4020.000000
mean         1.472139     1.650995          0.366667
std          3.307643     3.176383          0.481954
min         -2.000000     0.000000          0.000000
25%          0.000000     0.000000          0.000000
50%          0.000000     0.000000          0.000000
75%          2.000000     2.000000          1.000000
max         32.000000    32.000000          1.000000


shipment_delayed
0    2546
1    1474
Name: count, dtype: int64

##Interpretation

This cell summarizes the newly created features and displays the distribution of delayed and non-delayed shipments. It verifies that the feature engineering process has been completed successfully and provides an overview of the target variable distribution.

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 86 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipment_id             4020 non-null   object
 1   booking_id              4020 non-null   object
 2   customer_id             4020 non-null   object
 3   product_id              4020 non-null   object
 4   carrier_id              4020 non-null   object
 5   warehouse_id            4020 non-null   object
 6   route_id                4020 non-null   object
 7   vehicle_id              4020 non-null   object
 8   customs_id              4020 non-null   object
 9   weather_id              4020 non-null   object
 10  booking_date            4020 non-null   datetime64[ns]
 11  ship_date               4020 non-null   datetime64[ns]
 12  expected_delivery_date  4020 non-null   datetime64[ns]
 13  shipping_mode           4020 non-null   object
 14  shipment_type           4020 non-null   object
 15  priority                4020 non-null   object
 16  weight_kg               4020 non-null   float64
 17  volume_cbm              4020 non-null   float64
 18  declared_value          4020 non-null   float64
 19  insurance               4020 non-null   bool
 20  fragile_x               4020 non-null   bool
 21  carrier_name            4020 non-null   object
 22  carrier_type            4020 non-null   object
 23  average_rating          4020 non-null   float64
 24  fleet_size              4020 non-null   float64
 25  years_of_service        4020 non-null   int64
 26  headquarters            4020 non-null   object
 27  customer_name           4020 non-null   object
 28  customer_type           4020 non-null   object
 29  industry                4020 non-null   object
 30  city_x                  4020 non-null   object
 31  state_x                 4020 non-null   object
 32  country                 4020 non-null   object
 33  registration_date       4020 non-null   datetime64[ns]
 34  customer_status         4020 non-null   object
 35  customs_required        4020 non-null   bool
 36  documentation_complete  4020 non-null   bool
 37  inspection_required     4020 non-null   bool
 38  cargo_type              4020 non-null   object
 39  destination_country_x   4020 non-null   object
 40  product_name            4020 non-null   object
 41  category                4020 non-null   object
 42  hs_code                 4020 non-null   float64
 43  hazardous               4020 non-null   bool
 44  perishable              4020 non-null   bool
 45  temperature_controlled  4020 non-null   bool
 46  fragile_y               4020 non-null   bool
 47  weight_per_unit         4020 non-null   float64
 48  supplier_name           4020 non-null   object
 49  origin_city             4020 non-null   object
 50  destination_city        4020 non-null   object
 51  origin_country          4020 non-null   object
 52  destination_country_y   4020 non-null   object
 53  origin_port             4020 non-null   object
 54  destination_port        4020 non-null   object
 55  distance_km             4020 non-null   float64
 56  average_transit_days    4020 non-null   int64
 57  route_risk              4020 non-null   object
 58  traffic_index           4020 non-null   float64
 59  history_id              4020 non-null   object
 60  actual_delivery_date    4020 non-null   datetime64[ns]
 61  delivery_status         4020 non-null   object
 62  delivery_attempts       4020 non-null   float64
 63  vehicle_number          4020 non-null   object
 64  vehicle_type            4020 non-null   object
 65  capacity_kg             4020 non-null   int64
 66  fuel_type               4020 non-null   object
 67  maintenance_status      4020 non-null   object
 68  vehicle_age             4020 non-null   int64
 69  warehouse_name          4020 non-null   object
 70  city_y                  4020 non-null   object
 71  state_y                 4020 non-null   object
 72  warehouse_capacity      4020 non-null   float64
 73  current_utilization     4020 non-null   float64
 74  warehouse_type          4020 non-null   object
 75  city                    4020 non-null   object
 76  forecast_date           4020 non-null   datetime64[ns]
 77  weather_condition       4020 non-null   object
 78  temperature             4020 non-null   float64
 79  rainfall                4020 non-null   float64
 80  humidity                4020 non-null   float64
 81  wind_speed              4020 non-null   float64
 82  visibility              4020 non-null   float64
 83  shipment_delay          4020 non-null   int64
 84  delay_days              4020 non-null   int64
 85  shipment_delayed        4020 non-null   int64
dtypes: bool(9), datetime64[ns](6), float64(17), int64(7), object(47)
memory usage: 2.4+ MB

##Interpretation

This cell displays the updated structure of the dataset after feature engineering. The additional columns—shipment_delay, delay_days, and shipment_delayed—confirm that the dataset is now enriched with features required for exploratory data analysis and machine learning.

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [74]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [75]:
from google.colab import files
files.download("cleaned_merged_dataset.csv")

In [76]:
import pandas as pd
import numpy as np

df1 = pd.read_csv('/content/drive/MyDrive/DATA SET /carriers.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DATA SET /customers.csv')
df3 = pd.read_csv('/content/drive/MyDrive/DATA SET /customs.csv')
df4 = pd.read_csv('/content/drive/MyDrive/DATA SET /products.csv')
df5 = pd.read_csv('/content/drive/MyDrive/DATA SET /routes.csv')
df6 = pd.read_csv('/content/drive/MyDrive/DATA SET /shipment_delivery_history.csv')
df7 = pd.read_csv('/content/drive/MyDrive/DATA SET /shipments.csv')
df8 = pd.read_csv('/content/drive/MyDrive/DATA SET /vehicles.csv')
df9 = pd.read_csv('/content/drive/MyDrive/DATA SET /warehouses.csv')
df10 = pd.read_csv('/content/drive/MyDrive/DATA SET /weather.csv')

dataframes = {
    'df1': df1, 'df2': df2, 'df3': df3, 'df4': df4, 'df5': df5,
    'df6': df6, 'df7': df7, 'df8': df8, 'df9': df9, 'df10': df10
}

for name, dataframe in dataframes.items():
    if 'hs_code' in dataframe.columns:
        print(f"The 'hs_code' column is found in {name}")

The 'hs_code' column is found in df4

In [77]:
df4.head()

,product_id,product_name,category,hs_code,hazardous,perishable,temperature_controlled,fragile,weight_per_unit,supplier_name
0,11ee7365-3de8-4f2e-b4b2-fc0202a0f2c3,Local Automotive Part,Automotive Parts,4022.33,False,False,True,False,7.09,Jones-Williams
1,257ace85-8350-43e8-b2f2-6161a558e97a,See Pharmaceutical,Pharmaceuticals,8365.85,False,True,False,False,16.25,Johnson LLC
2,0dad9f1e-5893-4421-b3a7-5cfec833e6ba,Raise Textile,Textiles,2667.78,False,False,False,False,31.80,Byrd and Sons
3,43fac5b7-251a-479f-88f3-c5a8e89e838d,Wonder Furniture,Furniture,9646.91,False,False,False,True,4.39,"Sanchez, Thompson and Moore"
4,373483cd-db6a-4d99-adec-0b6f9981f1ea,Opportunity Food & Beverage,Food & Beverage,8501.89,False,False,False,False,14.26,Mullen-Hall

In [78]:
master_df.isnull().sum().sum()

np.int64(2922)

In [79]:
missing = master_df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

hs_code                   262
fleet_size                252
supplier_name             245
visibility                232
industry                  230
current_utilization       166
wind_speed                165
weight_per_unit           141
inspection_required       128
maintenance_status        124
declared_value            117
traffic_index             113
state_x                   102
volume_cbm                 87
humidity                   83
priority                   83
fuel_type                  80
delivery_attempts          78
documentation_complete     73
route_risk                 66
customer_type              49
registration_date          46
dtype: int64

In [80]:
master_df.dtypes

shipment_id     object
booking_id      object
customer_id     object
product_id      object
carrier_id      object
                ...
temperature    float64
rainfall       float64
humidity       float64
wind_speed     float64
visibility     float64
Length: 83, dtype: object

In [81]:
numerical_cols = [
    'hs_code',
    'fleet_size',
    'visibility',
    'current_utilization',
    'wind_speed',
    'weight_per_unit',
    'declared_value',
    'traffic_index',
    'volume_cbm',
    'humidity',
    'delivery_attempts'
]

for col in numerical_cols:
    master_df[col] = master_df[col].fillna(master_df[col].median())

##Interpretation

Missing values in numerical columns are replaced with the median value of each column. This preserves the overall distribution of the data while minimizing the influence of extreme values.

In [82]:
categorical_cols = [
    'supplier_name',
    'industry',
    'inspection_required',
    'maintenance_status',
    'state_x',
    'priority',
    'fuel_type',
    'documentation_complete',
    'route_risk',
    'customer_type'
]

for col in categorical_cols:
    master_df[col] = master_df[col].fillna(master_df[col].mode()[0])

/tmp/ipykernel_678/3183692316.py:15: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  master_df[col] = master_df[col].fillna(master_df[col].mode()[0])

##Interpretation

Missing values in categorical columns are replaced with the most frequently occurring category (mode). This ensures that no missing categorical values remain while maintaining consistency in the dataset.

In [83]:
master_df['registration_date'] = master_df['registration_date'].fillna(
    master_df['registration_date'].mode()[0]
)

In [84]:
master_df.isnull().sum().sort_values(ascending=False)

shipment_id    0
booking_id     0
customer_id    0
product_id     0
carrier_id     0
              ..
temperature    0
rainfall       0
humidity       0
wind_speed     0
visibility     0
Length: 83, dtype: int64

In [85]:
print("Total Missing Values :", master_df.isnull().sum().sum())
print("Duplicate Rows :", master_df.duplicated().sum())
print("Dataset Shape :", master_df.shape)

Total Missing Values : 0
Duplicate Rows : 0
Dataset Shape : (4020, 83)

In [86]:
master_df.to_csv('cleaned_merged_dataset_v3.csv', index=False)

In [87]:
from google.colab import files

files.download('cleaned_merged_dataset_v3.csv')